http:
  middlewares:
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    user-auth:
      basicAuth:
        users:
          - '{{ env "TRAEFIK_AUTH" }}'

    redirect-to-non-www:
      redirectRegex:
        regex: "^https?://www\\.(.+)"
        replacement: "https://${1}"
        permanent: true

  routers:
    redirect-www-http:
      rule: "HostRegexp(`www.{domain:.+}`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-non-www
      service: noop@internal

    redirect-www-https:
      rule: "HostRegexp(`www.{domain:.+}`)"
      entryPoints:
        - websecure
      middlewares:
        - redirect-to-non-www
      tls:
        # you cant redirect https://www to https://non-www without resolving certificate
        certResolver: letsencrypt
      service: noop@internal

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12
