<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Mon, 05 Jun 2017 08:47:42 +0000
// --------------------------------------------------------------------------------

$l['nav_announcements'] = 'Obavijesri Foruma';
$l['announcements'] = 'Obavijesti';
$l['forum_announcement'] = 'Obavijesti foruma: {1}';
$l['error_invalidannouncement'] = 'Obavijest koju ste unijeli nije ispravna.';
$l['announcement_edit'] = 'Uredi ovu obavijest';
$l['announcement_qdelete'] = 'Izbriši ovu obavijest';
$l['announcement_quickdelete_confirm'] = 'Jeste li sigurni da želite izbrisati ovu obavijest?';
