<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 11:27:14 +0000
// --------------------------------------------------------------------------------

$l['nav_calendar'] = 'Kalendar';
$l['nav_viewevent'] = 'Pregled događaja';
$l['nav_dayview'] = 'Pregled dana';
$l['nav_addevent'] = 'Dodaj događaj';
$l['nav_editevent'] = 'Uredi događaj';
$l['nav_move_event'] = 'Premjesti događaj';
$l['calendar_disabled'] = 'Ne možete koristiti kalendar pošto ga je administrator onemogućio.';
$l['alt_month_1'] = 'Siječanj';
$l['alt_month_2'] = 'Veljača';
$l['alt_month_3'] = 'Ožujak';
$l['alt_month_4'] = 'Travanj';
$l['alt_month_5'] = 'Svibanj';
$l['alt_month_6'] = 'Lipanj';
$l['alt_month_7'] = 'Srpanj';
$l['alt_month_8'] = 'Kolovoz';
$l['alt_month_9'] = 'Rujan';
$l['alt_month_10'] = 'Listopad';
$l['alt_month_11'] = 'Studeni';
$l['alt_month_12'] = 'Prosinac';
$l['add_private_event'] = 'Dodaj privatni događaj';
$l['add_public_event'] = 'Dodaj javni događaj';
$l['calendar'] = 'Kalendar';
$l['jump_month'] = 'Skoči na mjesec:';
$l['birthdays_on_day'] = 'Rođendana na {1}';
$l['birthdayhidden'] = 'skriven';
$l['event'] = 'događaj';
$l['events'] = 'događaji';
$l['add_event'] = 'Dodaj događaj';
$l['event_date'] = 'Datum događaja:';
$l['event_recurring_start_date'] = 'Datum početka:';
$l['event_recurring_end_date'] = 'Datum kraja:';
$l['event_recurring_repeat_days'] = 'Događaj se ponavlja svaki:';
$l['event_name'] = 'Ime događaja:';
$l['event_details'] = 'Detalji događaja:';
$l['event_options'] = 'Postavke:';
$l['private_option'] = '<b>Privatno</b> Samo vi možete vidjeti ovaj događaj. (Samo za registrirane korisnikev).';
$l['delete_option'] = '<b>Izbriši:</b> Izbriši ovaj događaj.';
$l['post_event'] = 'Pošalji događaj';
$l['day_view'] = 'Pregled dana';
$l['birthday'] = 'Rođendan';
$l['birthdays'] = 'Rođendani';
$l['event_author'] = 'Autor događaja:';
$l['edit_event'] = 'Uredi događaj';
$l['view_event'] = 'Pregled događaja';
$l['no_events'] = 'Nema događaja na ovaj dan.<p><a href="calendar.php?action=addevent&amp;calendar={1}&amp;day={2}&amp;month={3}&amp;year={4}">Dodajte događaj</a>.</p>';
$l['years_old'] = '{1} godina staro';
$l['alt_edit'] = 'Uredi ovaj događaj';
$l['alt_delete'] = 'Izbriši ovaj događaj';
$l['moderator_options'] = 'Mogućnosti uređivanja';
$l['approve_event'] = 'Odobri događaj';
$l['unapprove_event'] = 'Odbij događaj';
$l['move_event'] = 'Premjesti događaj';
$l['repeats_every_day'] = 'Ponavlja se svaki dan';
$l['repeats_every_x_days'] = 'Ponavlja se svakih {1} dana';
$l['repeats_on_weekdays'] = 'Ponavlja se od ponedeljka do petka';
$l['every_week_on_days'] = 'Ponavlja se svakog tjedna na {1}';
$l['every_week'] = 'Ponavlja se svakog tjedna';
$l['every_x_weeks_on_days'] = 'Ponavlja se svakih {1} tjedana na<br />{2}';
$l['every_x_weeks'] = 'Ponavlja se svakih {1} tjedana';
$l['every_month_on_day'] = 'Ponavlja se svaki {1}<br />svakog mjeseca';
$l['every_x_months_on_day'] = 'Ponavlja se svaki {1}<br />svakih {2} mjeseci';
$l['every_month_on_weekday'] = 'Ponavlja se na {1} {2}<br />svakog mjeseca';
$l['every_x_months_on_weekday'] = 'Ponavlja se na {1} {2}<br />svakih {3} mjeseci';
$l['weekday_occurance_1'] = 'prvo';
$l['weekday_occurance_2'] = 'drugo';
$l['weekday_occurance_3'] = 'treće';
$l['weekday_occurance_4'] = 'četvrto';
$l['weekday_occurance_last'] = 'zadnje';
$l['every_year_on_day'] = 'Ponavlja se svake godine na {1} {2}';
$l['every_x_years_on_day'] = 'Ponavlja se svake {3} godine na {1} {2}';
$l['every_year_on_weekday'] = 'Ponavlja se na {1} {2} u {3} svake godine';
$l['every_x_year_on_weekday'] = 'Ponavlja se na {1} {2} u {3} svake {4} godine';
$l['delete_event'] = 'Izbriši događaj';
$l['delete_q'] = 'Izbrisati?';
$l['delete_1'] = 'Za brisanje ovog događaja, označite kućicu lijevo a zatim kliknite na gumb desno.';
$l['delete_2'] = '<b>Pozor:</b> ovaj postupak se ne može poništiti.';
$l['delete_now'] = 'Izbriši odmah';
$l['jump_to_calendar'] = 'Skoči na kalendar:';
$l['select_calendar'] = 'Kalendar:';
$l['type_single'] = 'Jednodnevni događaj';
$l['type_ranged'] = 'Okviran ili ponavljajući događaj';
$l['enter_time'] = 'Vrijeme:';
$l['start_time'] = 'Početak:';
$l['end_time'] = 'Kraj:';
$l['timezone'] = 'Vremenska Zona:';
$l['ignore_timezone'] = '<strong>Ignoriraj vremensku zonu:</strong> Ovaj događaj će koristiti vremensku zonu posjetitelja.';
$l['repeats'] = 'Ponavlja se:';
$l['does_not_repeat'] = 'Ne ponavlja se';
$l['repeats_daily'] = 'dnevno';
$l['repeats_weekdays'] = 'svakog radnog dana (pon-pet)';
$l['repeats_weekly'] = 'tjedno';
$l['repeats_every'] = 'Ponavlja se svakih';
$l['day_or_days'] = 'dan(a)';
$l['week_or_weeks_on'] = 'tjedan(a) na';
$l['repeats_monthly'] = 'mjesečno';
$l['repeats_yearly'] = 'godišnje';
$l['repeats_on_day'] = 'ponavlja se na';
$l['of_every'] = 'svakog';
$l['month_or_months'] = 'mjeseca(i)';
$l['repeats_on_the'] = 'Ponavlja se na';
$l['day_of_every'] = 'dan svaki';
$l['repeats_on'] = 'Ponavlja se na';
$l['every'] = 'svaki';
$l['year_or_years'] = 'godine(a)';
$l['of'] = 'od';
$l['move_to_calendar'] = 'Premjesti u kalendar:';
$l['weekly_overview'] = 'Tjedni pregled';
$l['previous_week'] = 'Prethodni tjedan';
$l['next_week'] = 'Slijedeći tjedan';
$l['first'] = 'Prvo';
$l['second'] = 'Drugo';
$l['third'] = 'Treće';
$l['fourth'] = 'Četvrto';
$l['last'] = 'Zadnje';
$l['all_day'] = 'Cijeli dan';
$l['starts'] = 'Početak: ';
$l['finishes'] = 'Kraj: ';
$l['error_incorrectday'] = 'Dan koji ste unijeli ne postoji. Molimo vas da se vratite natrag i pokušate ponovno';
$l['error_invalidevent'] = 'Događaj koji ste unijeli nije ispravan ili ne postoji.';
$l['invalid_calendar'] = 'Navedeni kalendar ne postoji. Jeste li sigurni da ste posjetili pravu stranicu?';
$l['redirect_eventdeleted'] = 'Događaj je uspješno obrisan.<br />Sada ćete biti vraćeni na kalendar.';
$l['redirect_eventupdated'] = 'Ovaj događaj je uspješno ažuriran.<br />Sada ćete biti vraćeni na njega.';
$l['redirect_eventadded'] = 'Vaš je događaj uspješno unesen.<br />Sada ćete biti odvedeni na njega.';
$l['redirect_eventadded_moderation'] = 'Vaš je događaj uspješno unesen, i zahtjeva odobravanje moderatora.<br />Sada ćete biti odvedeni natrag na kalendar.';
$l['redirect_eventunapproved'] = 'Vaš je događaj uspješno odbijen.<br />Sada ćete biti odvedeni na njega.';
$l['redirect_eventapproved'] = 'Vaš je događaj uspješno odobren.<br />Sada ćete biti odvedeni na njega.';
$l['redirect_eventmoved'] = 'Vaš je događaj uspješno premješten.<br />Sada ćete biti odvedeni na njega.';
$l['delete_no_checkbox'] = 'Događaj nije izbrisan jer niste označili kućicu "Izbriši".';
