<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 11:33:33 +0000
// --------------------------------------------------------------------------------

$l['postdata_invalid_user_id'] = 'Korisnički id ne postoji. Molimo unesite ispravan korisnički id.';
$l['postdata_firstpost_no_subject'] = 'Niste unijeli naslov za temu. Molimo upišite naslov.';
$l['postdata_missing_subject'] = 'Niste unijeli naslov. Molimo upišite naslov.';
$l['postdata_missing_message'] = 'Niste unijeli poruku. Molimo napišite poruku.';
$l['postdata_message_too_long'] = 'Poruka je preduga. Molimo upišite poruku kraću od {1} znakova (trenutno {2}).';
$l['postdata_message_too_short'] = 'Poruka je prekratka. Molimo upišite poruku dužu od {1} znakova.';
$l['postdata_subject_too_long'] = 'Naslov je predug. Molimo upišite naslov kraći od 85 znakova (trenutno {1}).';
$l['postdata_banned_username'] = 'Korisničko ime koje ste unijeli ne može biti registrirano. Molimo unesite drugo korisničko ime.';
$l['postdata_bad_characters_username'] = 'Korisničko ime koje ste unijeli sadrži nepoželjne znakove. Molimo unesite drugo korisničko ime.';
$l['postdata_invalid_username_length'] = 'Korisničko ime koje ste unijeli nije ispravne dužine. Molimo unesite korisničko ime između {1} i {2} znakova.';
$l['postdata_post_flooding'] = 'Prebrzo pokušavate poslati slijedeću poruku. Molimo pričekajte još {1} sekundi.';
$l['postdata_post_flooding_one_second'] = 'Prebrzo pokušavate poslati slijedeću poruku. Molimo pričekajte još 1 sekundu.';
$l['postdata_too_many_images'] = 'Poruka koju ste unijeli sadrži {1} slika, a dozvoljeno je {2} slika po poruci. Molimo smanjite broj slika u vašoj poruci.';
$l['postdata_too_many_videos'] = 'Poruka koju ste unijeli sadrži {1} videa, a dozvoljeno je {2} videa po poruci. Molimo smanjite broj videa u vašoj poruci.';
$l['postdata_invalid_prefix'] = 'Odabrani prefiks nije ispravan. Molimo odaberite ispravni prefiks.';
$l['postdata_require_prefix'] = 'Ovaj forum zahtijeva da postavite prefiks teme. Molimo odaberite valjani prefiks.';
$l['thread_closed'] = 'Tema zatvorena';
$l['thread_opened'] = 'Tema otvorena';
$l['thread_stuck'] = 'Tema zalijepljena';
$l['thread_unstuck'] = 'Tema odlijepljena';
$l['postdata_username_exists'] = 'Korisničko ime koje ste unijeli već postoji. Molimo unesite drugo korisničko ime.';
