<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 11:33:43 +0000
// --------------------------------------------------------------------------------

$l['warnings_reached_max_warnings_day'] = 'Nikog više ne možete opominjati jer ste dosegli ograničenje broja opomena koje možete podijeliti u jednom danu.<br /><br />Najveći broj opomena koji možete dati dnevno je {1}."';
$l['warnings_error_invalid_user'] = 'Izabrani korisnik ne postoji.';
$l['warnings_error_invalid_post'] = 'Izabrana poruka ne postoji.';
$l['warnings_error_cannot_warn_self'] = 'Ne možete sami sebi povećati nivo opomene.';
$l['warnings_error_user_reached_max_warning'] = 'Ovaj korisnik ne može biti opomenut jer je već dostigao najveći nivo opomene.';
$l['warnings_error_no_note'] = 'Niste unijeli nikakve administrativne bilješke za ovu opomenu.';
$l['warnings_error_invalid_type'] = 'Niste izabrali isporavan tip opomene.';
$l['warnings_error_cant_custom_warn'] = 'Nemate dozvolu korisnicima davati vlastite opomene.';
$l['warnings_error_no_custom_reason'] = 'Niste unijeli razlog vaše vlastite opomene.';
$l['warnings_error_invalid_custom_points'] = 'Niste unijeli valjan broj bodova za dodavanje ovom nivou opomene. Trebate unijeti brojevnu vrijednost veću od 0 ali manju od {1}.';
$l['warnings_error_invalid_expires_period'] = 'Niste unijeli ispravan tip isteka.';
