<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 11:34:20 +0000
// --------------------------------------------------------------------------------

$l['nav_editpost'] = 'Uredi poruku';
$l['edit_post'] = 'Uredi ovu poruku';
$l['delete_post'] = 'Izbriši poruku';
$l['delete_q'] = 'Izbrisati?';
$l['delete_1'] = 'Za brisanje ove poruke, označite kućicu sa lijeve strane, a zatim kliknite na gomb \'Izbriši\'.';
$l['delete_2'] = '<b>Pažnja:</b> Ako je ova poruka prva u temi, njenim ćete brisanjem obrisati i cijelu temu.';
$l['subject'] = 'Naslov';
$l['your_message'] = 'Vaša poruka';
$l['post_options'] = 'Postavke slanja:';
$l['editreason'] = 'Razlog uređivanja:';
$l['options_sig'] = '<strong>Potpis:</strong> uključuje vaš potpis. (samo registrirani korisnici)';
$l['options_emailnotify'] = '<strong>E-mail Obavijesti:</strong> primanje e-maila kad god ima novih odgovora. (samo registrirani korisnici)';
$l['options_disablesmilies'] = '<strong>Onemogući emotikone:</strong> onemogući prikaz emotikona u ovoj poruci.';
$l['preview_post'] = 'Pregled poruke';
$l['update_post'] = 'Prihvati promjene';
$l['poll'] = 'Anketa:';
$l['poll_desc'] = 'Možete dodati anketu ovoj poruci.';
$l['poll_check'] = 'Želim dodati anketu';
$l['num_options'] = 'Broj opcija:';
$l['max_options'] = '(Najviše: {1})';
$l['delete_now'] = 'Odmah izbriši';
$l['edit_time_limit'] = 'Žao nam je ali ne možete urediti svoju poruku. Uređivanje poruka moguće samo {1} minuta od objave.';
$l['no_prefix'] = 'Bez prefiksa';
$l['redirect_nodelete'] = 'Poruka nije izbrisana jer niste označili kućicu "Izbriši".';
$l['redirect_norestore'] = 'Poruka nije vraćena jer niste označili kućicu "Vrati".';
$l['redirect_postedited'] = 'Zahvaljujemo, ova poruka je uređena.<br />';
$l['redirect_postedited_redirect'] = 'Sada ćete biti vraćeni na temu.';
$l['redirect_postedited_poll'] = 'Zahvaljujemo, poruka je uređena. <br />Pošto ste odabrali da želite dodati anketu biti ćete odvedeni na stranicu za postavljanje ankete.';
$l['error_invalidpost'] = 'Na žalost, izgleda da ste došli na ne ispravnu adresu. Molimo vas da provjerite da li izabrana poruka postoji, a zatim pokušajte ponovno.';
$l['redirect_threaddeleted'] = 'Zahvaljujemo, tema je izbrisana.<br />Sada ćete biti vraćeni na forum.';
$l['redirect_postdeleted'] = 'Zahvaljujemo, poruka je izbrisana.<br />Sada ćete biti vraćeni na temu.';
$l['redirect_threadrestored'] = 'Zahvaljujemo, tema je vraćena.<br />Sada ćete biti vraćeni na forum.';
$l['redirect_postrestored'] = 'Zahvaljujemo, poruka je vraćena.<br />Sada ćete biti vraćeni na temu.';
$l['redirect_threadclosed'] = 'Ne možete uređivati poruke u ovoj temi jer ju je moderator zatvorio.';
$l['redirect_post_moderation'] = 'Administrator je izabrao da su potrebna odobrenja za uređivanje poruka. Sada ćete biti vraćeni na temu.';
$l['redirect_thread_moderation'] = 'Administrator je izabrao da su potrebna odobrenja za uređivanje poruka. Sada ćete biti vraćeni na početnu stranicu foruma.';
$l['error_already_delete'] = 'Žao nam je, ali ova poruka je već izbrisana.';
$l['thread_deleted'] = 'Tema trajno izbrisana';
$l['post_deleted'] = 'Poruka trajno izbrisana';
$l['thread_soft_deleted'] = 'Privremeno izbrisana tema';
$l['post_soft_deleted'] = 'Privremeno izbrisana poruka';
$l['thread_restored'] = 'Vraćena tema';
$l['post_restored'] = 'Vraćena poruka';
$l['error_already_deleted'] = 'Odabrana poruka je već izbrisana.';
