<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 11:38:36 +0000
// --------------------------------------------------------------------------------

$l['hello'] = 'Pozdrav svijete!';
$l['hello_add'] = 'Dodaj';
$l['hello_add_message'] = 'Dodaj poruku';
$l['hello_empty'] = 'Poruke nisu pronađene.';
$l['hello_message_empty'] = 'Poruka ne može biti prazna.';
$l['hello_done'] = 'Uspiješno dodana nova poruka';
