<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 11:40:12 +0000
// --------------------------------------------------------------------------------

$l['s1_name'] = 'User Maintenance';
$l['s1_desc'] = 'Basic instructions for maintaining a forum account.';
$l['s2_name'] = 'Pisanje';
$l['s2_desc'] = 'Pisanje, odgovaranje i osnovno korištenje foruma.';
