<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1813
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sun, 19 Apr 2020 13:27:49 +0000
// --------------------------------------------------------------------------------

$l['boardstats'] = 'Statistika foruma';
$l['new_posts'] = 'Forum sadrži nove poruke';
$l['no_new_posts'] = 'Forum ne sadrži nove poruke';
$l['forum_locked'] = 'Forum je zaključan';
$l['forum_unapproved_posts_count'] = 'Trenutno ima {1} neodobrenih poruka u ovom forumu.';
$l['forum_unapproved_post_count'] = 'Trenutno ima 1 neodobrena poruka u ovom forumu.';
$l['forum_unapproved_threads_count'] = 'Trenutno ima {1} neodobrenih tema u ovom forumu..';
$l['forum_unapproved_thread_count'] = 'Trenutno ima 1 neodobrena tema u ovom forumu.';
$l['markread'] = 'Označi sve forume pročitanima';
$l['forumteam'] = 'Tim foruma';
$l['forumstats'] = 'Statistika foruma';
$l['todays_birthdays'] = 'Današnji rođendani';
$l['birthdayhidden'] = 'Skriveno';
$l['quick_login'] = 'Brza prijava:';
$l['index_logout'] = 'Odjava';
$l['private_messages'] = 'Privatne poruke';
$l['pms_new'] = 'Imate {1} novih poruka od posljednje posjete.';
$l['pms_unread_total'] = '(Imate {1} nepročitanih poruka i {2} poruka ukupno u vašim mapama.)';
$l['stats_posts_threads'] = 'Naši članovi su poslali ukupno {1} poruka u {2} tema.';
$l['stats_numusers'] = 'Trenutno imamo {1} registrovanih članova.';
$l['stats_newestuser'] = 'Molimo pozdravite našeg najnovijeg člana, <b>{1}</b>';
$l['stats_mostonline'] = 'Najviše korisnika na forumu odjednom je bilo {1} dana {2} u {3}';
$l['whos_online'] = 'Tko je na forumu';
$l['complete_list'] = 'Potpuni popis';
$l['online_online_plural'] = 'korisnika';
$l['online_online_singular'] = 'korisnik';
$l['online_member_plural'] = 'članova';
$l['online_member_singular'] = 'član';
$l['online_anon_plural'] = 'su';
$l['online_anon_singular'] = 'je';
$l['online_guest_plural'] = 'gosta';
$l['online_guest_singular'] = 'gost';
$l['online_note'] = '{1} {2} je bilo u proteklih {3} minuta ({4} {5}, od čega {7} {6} skrivenih, i {8} {9}).';
$l['subforums'] = '<strong>Pod forumi:</strong>';
$l['forum_closed'] = 'Forum je Zatvoren';
$l['board_stats_link_separator'] = ' | ';
