<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1813
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sun, 19 Apr 2020 13:33:44 +0000
// --------------------------------------------------------------------------------

$l['nav_memberlist'] = 'Popis članova';
$l['memberlist_disabled'] = 'Popis članova je onemogućen od strane Administratora.';
$l['member_list'] = 'Popis članova';
$l['avatar'] = 'Avatar';
$l['username'] = 'Korisničko ime';
$l['joined'] = 'Pridružen';
$l['lastvisit'] = 'Posljednja posjeta';
$l['posts'] = 'Broj poruka';
$l['threads'] = 'Broj tema';
$l['referrals'] = 'Preporučenih članova';
$l['search_members'] = 'Pretraga popisa članova';
$l['website'] = 'Web stranica';
$l['sort_by'] = 'Složi po';
$l['contains'] = 'Sadrži:';
$l['sort_by_username'] = 'Složi po: Korisničkom imenu';
$l['sort_by_regdate'] = 'Složi po: Datumu registracije';
$l['sort_by_lastvisit'] = 'Složi po : Posljednjoj posjeti';
$l['sort_by_posts'] = 'Složi po: Broju poruka';
$l['sort_by_threads'] = 'Složi po: Broju tema';
$l['sort_by_referrals'] = 'Složi po: Preporučenih članova';
$l['order_asc'] = 'uzlaznim redoslijedom';
$l['order_desc'] = 'silaznim redoslijedom';
$l['asc'] = 'uzlazno';
$l['desc'] = 'silazno';
$l['forumteam'] = 'Prikaži tim foruma';
$l['advanced_search'] = 'Napredna pretraga';
$l['nav_memberlist_search'] = 'Traži';
$l['search_member_list'] = 'Pretraga popisa članova';
$l['search_criteria'] = 'Kriteriji pretrage';
$l['begins_with'] = 'počinje sa';
$l['username_contains'] = 'sadrži';
$l['search_website'] = 'URL web stranice';
$l['search_aim'] = 'AIM Screen ime';
$l['search_skype'] = 'Skype adresa';
$l['search_google'] = 'Google Talk adresa';
$l['search_yahoo'] = 'Yahoo! Messenger Screen ime';
$l['search_icq'] = 'ICQ broj';
$l['search_options'] = 'Postavke pretrage';
$l['per_page'] = 'Rezultata po stranici';
$l['search'] = 'Pretraga';
$l['search_user'] = 'Traži korisnika';
$l['error_no_members'] = '<p>Nema pronađenih članova po kriterijima pretrage koje ste unijeli.</p><p>Molimo unesite druge kriterije pretrage i pokušajte ponovo.</p>';
$l['a'] = 'A';
$l['b'] = 'B';
$l['c'] = 'C';
$l['d'] = 'D';
$l['e'] = 'E';
$l['f'] = 'F';
$l['g'] = 'G';
$l['h'] = 'H';
$l['i'] = 'I';
$l['j'] = 'J';
$l['k'] = 'K';
$l['l'] = 'L';
$l['m'] = 'M';
$l['n'] = 'N';
$l['o'] = 'O';
$l['p'] = 'P';
$l['q'] = 'Q';
$l['r'] = 'R';
$l['s'] = 'S';
$l['t'] = 'T';
$l['u'] = 'U';
$l['v'] = 'V';
$l['w'] = 'W';
$l['x'] = 'X';
$l['y'] = 'Y';
$l['z'] = 'Z';
$l['username_exact'] = 'točno';
