<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:13:38 +0000
// --------------------------------------------------------------------------------

$l['nav_newreply'] = 'Odgovori';
$l['post_reply_to'] = 'Odgovori na {1}';
$l['post_new_reply'] = 'Napiši odgovor';
$l['reply_to'] = 'Odgovori na temu: {1}';
$l['post_subject'] = 'Naziv posta:';
$l['your_message'] = 'Vaša poruka:';
$l['post_options'] = 'Opcije posta:';
$l['options_sig'] = '<strong>Potpis:</strong> uključi vaš potpis. (samo za registrirane korisnike)';
$l['options_emailnotify'] = '<strong>Obavijesti e-mailom:</strong> primi e-mail kad god je napisan novi odgovor. (samo za registrirane korisnike)';
$l['options_disablesmilies'] = '<strong>Onemogući smajliće:</strong> onemogući smajliće koji se prikazuju u postu.';
$l['post_reply'] = 'Odgovori';
$l['preview_post'] = 'Pregledaj poruku';
$l['mod_options'] = 'Moderatorska opcije:';
$l['close_thread'] = '<strong>Zatvori temu</strong>: onemogući pisanje u ovoj temi ubuduće.';
$l['stick_thread'] = '<strong>Zalijepi temu:</strong> zalijepi temu na vrh foruma.';
$l['forum_rules'] = '{1} - Pravila';
$l['thread_review'] = 'Pregled teme (najnovije prvo)';
$l['thread_review_more'] = 'Ova tema ima više od {1} odgovora. <a href="{2}">Pročitaj ovu cijelu temu.</a>';
$l['posted_by'] = 'Napisano od';
$l['draft_saved'] = 'Poruka je automatski spremljena kao skica.<br />Sada ćete biti vraćeni na popis skica.';
$l['error_post_already_submitted'] = 'Već ste napisali ovaj odgovor na ovu temu. Molimo posjetite temu da biste vidjeli vaš odgovor.';
$l['multiquote_external_one'] = 'Izabrali ste jedan post izvan ove teme.';
$l['multiquote_external'] = 'Izabrali ste {1} postova izvan ove teme.';
$l['multiquote_external_one_deselect'] = 'neodaberi ovaj post';
$l['multiquote_external_deselect'] = 'neodaberi ove postove';
$l['multiquote_external_one_quote'] = 'Citiraj i ovaj post';
$l['multiquote_external_quote'] = 'Citiraj i ove postove';
$l['redirect_newreply'] = 'Hvala vam, vaš odgovor je poslan.';
$l['redirect_newreply_moderation'] = 'Administrator je specifirao da novi postovi trebaju biti moderirani. Sada ćete biti vraćeni na temi.';
$l['redirect_newreply_post'] = '<br />Sada ćete biti vraćeni na post.';
$l['redirect_newreplyerror'] = 'Žao nam je, ali vaš odgovor je odbijen zbog nedostatka sadržaja. <br />Sada ćete biti vraćeni na temu.';
$l['redirect_threadclosed'] = 'Ne možete poslati odgovore u ovoj temi jer je ona zatvorena od administratora.';
$l['error_post_noperms'] = 'Nemate dopuštenje za uređivanje ove skice.';
$l['error_stop_forum_spam_spammer'] = 'Žao nam je, vaši {1} rezultati odgovaraju s poznatim spammerom. Ako mislite da je ovo greška, molimo kontaktirajte administratora';
$l['error_stop_forum_spam_fetching'] = 'Žao nam je, nešto je pošlo po krivu kod provjere databaze spamera. Najvjerojatnije se databazi ne može pristupiti. Molimo vas da pokušate ponovno.';
$l['error_suspendedposting'] = 'Vaše privilegije postanja su trenutno suspendirane {1}.<br /><br />

Datum suspenzije: {2}';
$l['error_suspendedposting_temporal'] = 'do {1}';
$l['error_suspendedposting_permanent'] = 'trajno';
