<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:13:25 +0000
// --------------------------------------------------------------------------------

$l['nav_newthread'] = 'Nova tema';
$l['newthread_in'] = 'Nova tema u {1}';
$l['post_new_thread'] = 'Pošaljite novu temu';
$l['thread_subject'] = 'Naslov teme';
$l['your_message'] = 'Vaša poruka:';
$l['post_options'] = 'Opcije pisanja:';
$l['options_sig'] = '<strong>Potpis:</strong> uključi vaš potpis. (samo za registrirane korisnike)';
$l['options_emailnotify'] = '<strong>Obavijesti e-mailom:</strong> primi e-mail kad god je napisan novi odgovor. (samo za registrirane korisnike)';
$l['options_disablesmilies'] = '<strong>Onemogući smajliće:</strong> onemogući smajliće koji se prikazuju u postu.';
$l['post_thread'] = 'Pošalji temu';
$l['preview_post'] = 'Pregledaj post';
$l['poll'] = 'Anketa:';
$l['poll_desc'] = 'Ako želite, možete dodati anketu ovoj temi.';
$l['poll_check'] = 'Želim dodati anketu';
$l['num_options'] = 'Broj pocija:';
$l['max_options'] = '(Najviše: {1})';
$l['mod_options'] = 'Moderatorska opcije:';
$l['close_thread'] = '<strong>Zatvori temu</strong>: onemogući pisanje u ovoj temi ubuduće.';
$l['stick_thread'] = '<strong>Zalijepi temu:</strong> zalijepi temu na vrh foruma.';
$l['draft_saved'] = 'Tema je uspješno spremljena kao skica.<br />Sada ćete biti vraćeni na popis skica.';
$l['error_post_already_submitted'] = 'Već ste poslali ovu temu u ovom forumu. Molimo posjetite forum kako biste vidjeli temu.';
$l['no_prefix'] = 'Bez prefiksa';
$l['forum_rules'] = '{1} - Pravila';
$l['multiquote_external_one'] = 'Izabrali ste jedan post izvan ove teme.';
$l['multiquote_external'] = 'Izabrali ste {1} postova izvan ove teme.';
$l['multiquote_external_one_deselect'] = 'neodaberi ovaj post';
$l['multiquote_external_deselect'] = 'neodaberi ove postove';
$l['multiquote_external_one_quote'] = 'Citiraj i ovaj post';
$l['multiquote_external_quote'] = 'Citiraj i ove postove';
$l['redirect_newthread'] = 'Hvala vam, vaša tema je poslana.';
$l['redirect_newthread_poll'] = '<br />Sada ćete biti vraćenu na stranicu konfiguracije.';
$l['redirect_newthread_moderation'] = '<br />Administrator je specifirao da nove teme trebaju biti moderirane. Sada ćete biti vraćeni na popis tema.';
$l['redirect_newthread_thread'] = '<br />Sada ćete biti odvedeni na novu temu.';
$l['invalidthread'] = 'Navedena skica ne postoji ili nemate dopuštenja da biste je pregledali.';
$l['error_stop_forum_spam_spammer'] = 'Žao nam je, vaši {1} rezultati odgovaraju s poznatim spammerom. Ako mislite da je ovo greška, molimo kontaktirajte administratora';
$l['error_stop_forum_spam_fetching'] = 'Žao nam je, nešto je pošlo po krivu kod provjere databaze spamera. Najvjerojatnije se databazi ne može pristupiti. Molimo vas da pokušate ponovno.';
$l['error_suspendedposting'] = 'Vaše privilegije postanja su trenutno suspendirane {1}.<br /><br />

Datum suspenzije: {2}';
$l['error_suspendedposting_temporal'] = 'do {1}';
$l['error_suspendedposting_permanent'] = 'trajno';
$l['redirect_newthread_unviewable'] = '<br />Nemate dopuštenje da biste vidjeli teme u ovom forumu. Sada ćete biti vraćeni na početnu stranicu foruma.';
