<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:13:12 +0000
// --------------------------------------------------------------------------------

$l['nav_online'] = 'Tko je online';
$l['nav_onlinetoday'] = 'Tko je bio online danas';
$l['viewing_announcements'] = 'Pregledava obavijest <a href="{1}">{2}</a>';
$l['viewing_announcements2'] = 'Pregledava obavijest';
$l['viewing_attachment'] = 'Pregledava prilog';
$l['viewing_attachment2'] = 'Pregledava <a href="attachment.php?aid={1}" target="_blank">prilog</a> u temi <a href="{3}">{2}</a>';
$l['viewing_calendar'] = 'Pregledava <a href="calendar.php">kalendar</a>';
$l['viewing_event'] = 'Pregledava događaj';
$l['viewing_event2'] = 'Pregledava događaj <a href="{1}">{2}</a>';
$l['adding_event'] = '<a href="calendar.php?action=addevent">Dodaje događaj</a>';
$l['editing_event'] = 'Uređuje događaj';
$l['viewing_contact_us'] = 'Gleda <a href="contact.php">kontaktiraj nas</a>';
$l['editing_post'] = 'Uređuje post';
$l['viewing_forum'] = 'Gleda forum';
$l['viewing_forum2'] = 'Gleda forum <a href="{1}">{2}</a>';
$l['forum_redirect_to'] = 'Preusmjeren je na <a href="{1}">{2}</a>';
$l['viewing_index'] = '{1} <a href="index.php">Početna stranica</a>';
$l['activating_account'] = 'Čeka aktivaciju';
$l['viewing_profile'] = 'Gleda profil';
$l['viewing_profile2'] = 'Gleda profil od <a href="{1}">{2}</a>';
$l['registering'] = '<a href="member.php?action=register">Registrira se</a>';
$l['logging_in'] = '<a href="member.php?action=login">Prijavljuje se</a>';
$l['logging_in_plain'] = 'Prijavljuje se';
$l['logging_out'] = 'Odjavljuje se';
$l['emailing_user'] = 'Šalje e-mail korisniku';
$l['rating_user'] = 'Ocjenjuje korisnika';
$l['viewing_memberlist'] = 'Gleda <a href="memberlist.php">popis članova</a>';
$l['viewing_whoposted'] = 'Gleda tko je pisao';
$l['viewing_whoposted2'] = 'Gleda tko je pisao u temi <a href="{1}">{2}</a>';
$l['marking_read'] = '<a href="misc.php?action=markread&amp;my_post_key={1}">Označuje forume kao pročitane</a>';
$l['viewing_helpdocs'] = 'Gleda <a href="misc.php?action=help">Dokumente pomoći</a>';
$l['viewing_buddylist'] = 'Gleda <a href="#" onclick="MyBB.popupWindow(\'/misc.php?action=buddypopup&amp;modal=1\'); return false;">popis prijatelja</a>';
$l['viewing_smilies'] = 'Gleda <a href="misc.php?action=smilies">popis smajlića</a>';
$l['viewing_syndication'] = 'Gleda <a href="misc.php?action=syndication">RSS Syndication</a> stranicu';
$l['replying_thread'] = 'Odgovara na temu';
$l['replying_thread2'] = 'Odgovara na temu <a href="{1}">{2}</a>';
$l['posting_thread'] = 'Otvara novu temu';
$l['posting_thread2'] = 'Otvara novu temu u <a href="{1}">{2}</a>';
$l['viewing_wol'] = 'Gleda <a href="online.php">tko je online</a>';
$l['viewing_woltoday'] = 'Gleda <a href="online.php?action=today">tko je bio online danas</a>';
$l['creating_poll'] = 'Kreira novu anketu';
$l['editing_poll'] = 'Uređuje anketu';
$l['viewing_pollresults'] = 'Gleda rezultate ankete';
$l['voting_poll'] = 'Glasa u anketi';
$l['using_modtools'] = 'Koristi moderatorske alate';
$l['sending_pm'] = 'Šalje privatnu poruku';
$l['reading_pm'] = 'Čita privatnu poruku';
$l['editing_pmfolders'] = 'Uređuje mape privatnih poruka';
$l['using_pmsystem'] = 'Korištenje PP sistema';
$l['reporting_post'] = 'Prijavljuje post';
$l['searching_forum'] = '<a href="search.php">Pretražuje</a> {1}';
$l['reading_thread'] = 'Čita temu';
$l['reading_thread2'] = 'Čita temu <a href="{1}">{2}</a> {3}';
$l['viewing_team'] = 'Pregledava tim foruma';
$l['viewing_stats'] = 'Gleda statistiku foruma';
$l['updating_profile'] = '<a href="usercp.php?action=profile">Ažurira profil</a>';
$l['updating_options'] = '<a href="usercp.php?action=options">Ažurira opcije</a>';
$l['editing_signature'] = '<a href="usercp.php?action=editsig">Uređuje potpis</a>';
$l['changing_avatar'] = '<a href="usercp.php?action=avatar">Mijenja avatar</a>';
$l['viewing_subscriptions'] = 'Gleda <a href="usercp.php?action=subscriptions">pretplate na teme</a>';
$l['editing_pad'] = 'Uređuje <a href="usercp.php">vlastiti blok</a>';
$l['editing_password'] = 'Uređuje <a href="usercp.php?action=password">lozinku</a>';
$l['user_cp'] = 'Gleda <a href="usercp.php">Korisničku ploču</a>';
$l['viewing_portal'] = 'Gleda <a href="portal.php">portal</a>';
$l['viewing_noperms'] = 'Glada stranicu \\"bez dopuštenja\\"';
$l['unknown_location'] = '<a href="{1}">Nepoznata lokacija</a>';
$l['giving_reputation'] = 'Daje reputaciju za <a href="{1}">{2}</a>';
$l['viewing_reputation_report'] = 'Gleda <a href="{1}">{2} reputaciju</a>';
$l['viewing_reputation_report2'] = 'Gleda reoutaciju';
$l['member_resendactivation'] = 'Ponovno šalje link za aktivaciju računa e-mailom';
$l['member_lostpw'] = 'Vraća <a href="member.php?action=lostpw">izgubljenu lozinku</a>';
$l['sending_thread'] = 'Šalje temu prijatelju';
$l['guest'] = 'Gost';
$l['page'] = 'Stranica';
$l['users_online'] = 'Tko je online';
$l['on_username'] = 'Korisničko ime';
$l['time'] = 'Vrijeme';
$l['location'] = 'Lokacija';
$l['online_today'] = 'Tko je online danas';
$l['refresh_page'] = 'Osvježi ovu sranicu';
$l['online_online_plural'] = 'korisnici';
$l['online_online_singular'] = 'korisnik';
$l['online_member_plural'] = 'članovi';
$l['online_member_singular'] = 'član';
$l['online_anon_plural'] = 'su';
$l['online_anon_singular'] = 'je';
$l['online_guest_plural'] = 'gosti';
$l['online_guest_singular'] = 'gost';
$l['online_count'] = '{1} {2} aktivnih u zadnjih {3} minuta ({4} {5}, {6} od kojih {7} nevidljivih, i {8} {9}).';
$l['ip'] = 'IP:';
$l['resolves_to'] = 'Host Name:';
$l['if_resolvable'] = '(if resolvable)';
$l['admin_options'] = 'Administratorske opcije';
$l['search_regip_users'] = 'Traži korisnike koji su se registrirali ovom IP adresom';
$l['search_postip_users'] = 'Traži korisnike koji su pisali s ovog IP-a';
$l['lookup'] = '[potraži]';
$l['member_online_today'] = '<strong>1</strong> korisnik je bio online danas';
$l['members_were_online_today'] = '<strong>{1}</strong> korisnika je bio online danas';
$l['member_online_hidden'] = ' ({1} korisnik je nevidljiv)';
$l['members_online_hidden'] = ' ({1} korisnika su nevidljivi)';
$l['rating_thread'] = 'Ocijenjuje temu';
$l['viewing_imcenter'] = 'Pregledava IM centar';
$l['managing_favorites'] = 'Upravlja najdražim temema';
$l['managing_subscriptions'] = 'Upravlja pretplaćenim temama';
$l['managing_group'] = 'Upravlja korisničkom grupom';
$l['viewing_modcp'] = 'Pregledava moderatorsku ploču';
$l['viewing_modlogs'] = 'Gleda moderatorske evidencije';
$l['managing_announcements'] = 'Upravlja obavijestima';
$l['search_for_user'] = 'Traži korisnike';
$l['managing_warninglogs'] = 'Upravlja evidencijom upozorenja';
$l['searching_ips'] = 'Treži IP adrese';
$l['viewing_reports'] = 'Gleda prijavljene postove';
$l['adding_announcement'] = 'Dodaje obavijest';
$l['deleting_announcement'] = 'Briše obavijest';
$l['editing_announcement'] = 'Uređuje obavijest';
$l['managing_modqueue'] = 'Upravlja Moderation Queue';
$l['editing_user_profiles'] = 'Uređuje korisničke profile';
$l['managing_bans'] = 'Upravlja banovima';
$l['revoking_warning'] = 'Miče upozorenje';
$l['warning_user'] = 'Upozorava korisnika';
$l['viewing_warning'] = 'Pregledava upozorenje';
$l['managing_warnings'] = 'Upraavlja upozorenjima';
$l['changing_dst'] = 'Mijenja DST promjenu';
$l['printing_thread'] = 'Ispisuje temu';
$l['printing_thread2'] = 'Ispisuje temu <a href="{1}">{2}</a>';
$l['managing_buddyignorelist'] = 'Upravlja popisom prijatelja/ignoriranih';
