<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:13:02 +0000
// --------------------------------------------------------------------------------

$l['nav_postpoll'] = 'Pošalji anketu';
$l['nav_editpoll'] = 'Uredi anketu';
$l['nav_pollresults'] = 'Rezultati ankete';
$l['edit_poll'] = 'Uredi anketu';
$l['delete_poll'] = 'Obriši anketu';
$l['delete_q'] = 'Obrisati?';
$l['delete_note'] = 'Da biste obrisali ovu anketu, oznaičite kućicu lijevo i kliknite gumb desno.';
$l['delete_note2'] = '<b>Pažnja:</b> Jednom kada obrišete anketu, ona više ne može biti vraćena.';
$l['question'] = 'Pitanje:';
$l['num_options'] = 'Broj opcija:';
$l['max_options'] = 'Najviše:';
$l['poll_options'] = 'Opcije:';
$l['update_options'] = 'Ažuriraj opcije';
$l['poll_options_note'] = 'Opcije ankete moraju biti kratke i jasne';
$l['options'] = 'Opcije:';
$l['option_multiple'] = '<b>Dozvoli više odabira:</b> Dopušta korisnicima da glasaju za više od jedne opcije odjednom.';
$l['option_multiple_maxoptions'] = 'Najveći broj opcija po korisniku (0 za bez ograničenja):';
$l['option_public'] = '<b>Javna anketa:</b>Daje korisnicima mogućnost da vide tko je glasao za koju opciju.';
$l['option_closed'] = '<b>Anketa je zatvorena:</b> Ako označite ovo, anketa će biti zatvorena za glasanje.';
$l['poll_timeout'] = 'Anketa istječe:';
$l['timeout_note'] = 'Broj dana koje korisnici mogu glasati u ovoj anketi.<br />(Postavite na 0 ako ne želite ograničiti vrijeme.)';
$l['days_after'] = 'dana nakon:';
$l['update_poll'] = 'Ažuriraj anketu';
$l['option'] = 'Opcija';
$l['votes'] = 'Glasova:';
$l['post_new_poll'] = 'Otvori novu anketu';
$l['days'] = 'dana';
$l['poll_results'] = 'Rezultati ankete';
$l['poll_total'] = 'Ukupno:';
$l['poll_votes'] = 'glas(ova)';
$l['redirect_pollposted'] = 'Vaša anketa je poslana.<br />Sada ćete biti vraćeni na temu.';
$l['redirect_pollpostedmoderated'] = 'Vaša anketa je poslana, ali vaša tema još uvijek čeka moderiranje.<br />Sada ćete biti vraćeni na forum.';
$l['redirect_pollupdated'] = 'Anketa je ažurirana.<br />Sada ćete biti vraćeni na temu.';
$l['redirect_votethanks'] = 'Hvala vam na glasanju.<br />Sada ćete biti vraćeni na temu.';
$l['redirect_unvoted'] = 'Vaši glasovi na ovoj temi su maknuti.<br />Sad ćete biti vraćeni na temu.';
$l['redirect_polldeleted'] = 'Hvala vam, vaša je anketa uspješno maknuta s teme.<br />Sada ćete biti vraćeni na temu.';
$l['error_polloptiontoolong'] = 'Jedan ili više opcija ankete je viška od dopuštenog limita. Molimo vas da se vratite natrag i smanjite njihov broj.';
$l['error_noquestionoptions'] = 'Vi ili niste unijeli pitanje ili vaša anketa nema dovoljno opcija. Najmanji broj opcija u anketi je 2.<br />Molimo vas da se vratite natrag i ispravite ovu grešku.';
$l['error_pollalready'] = 'Tema već ima anketu';
$l['error_nopolloptions'] = 'Navedena anketna opcija nije ispravna ili ne postoji.';
$l['error_maxpolloptions'] = 'Glasali ste za previše opcija. Dozvoljeno vam je glasati za {1} opcija.<br />Molimo vas da se vratite natrag i pokušate ponovno.';
$l['error_alreadyvoted'] = 'Već ste glasali u ovoj anketi.';
$l['error_notvoted'] = 'Niste glasali u ovoj anketi.';
$l['error_invalidpoll'] = 'Navedena anketa nije ispravna ili ne postoji.';
$l['error_pollclosed'] = 'Ne možete glasati u ovoj anketi jer je zatvorena.';
$l['poll_time_limit'] = 'Žao nam je ali ne možete dodati anketu u vašu temu. Administrator je zadao da ankete mogu biti postavljene tek {1} sati od pisanja.';
$l['poll_deleted'] = 'Obriši anketu';
$l['poll_edited'] = 'Uredi anketu';
$l['error_polloptionsequence'] = 'Jedna ili više opcija u anketi sadržava niz koji nije dopušten za korištenje: <strong>||~|~||</strong>. Molimo vas da se vratite i maknete to.';
