<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1813
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sun, 19 Apr 2020 13:39:12 +0000
// --------------------------------------------------------------------------------

$l['report_reason'] = 'Razlog prijave:';
$l['report_to_mod'] = 'Prijavi sadržaj moderaotru';
$l['close_window'] = 'Zatvori prozor';
$l['report_content'] = 'Prijavi sadržaj';
$l['report_reason_post'] = 'Prijavi post';
$l['report_reason_profile'] = 'Prijavi profil';
$l['report_reason_reputation'] = 'Prijavi reputaciju';
$l['report_reason_bad'] = 'Nepoželjan sadržaj';
$l['report_reason_spam'] = 'Spam';
$l['report_reason_rules'] = 'Krši pravila foruma';
$l['report_reason_wrong'] = 'Krivi forum';
$l['report_reason_other'] = 'Ostalo';
$l['success_report_voted'] = 'Hvala za prijavu sadržaja.<br />Član osoblja foruma će uskoro provijeriti vašu prijavu uskoro.';
$l['error_report_length'] = 'Molimo vas da detaljno napišete razlog vaše prijave.';
$l['error_invalid_report'] = 'Ovaj {1} ne postoji ili ga nije moguće prijaviti.';
$l['error_report_duplicate'] = 'Ovaj je sadržaj već prijavljen od strane nekog drugog člana foruma.<br />Vi ga također možete prijaviti.';
$l['report_reason_other_description'] = 'Ako izaberete \'ostalo\', molimo vas da navedete razlog za prijavu ovog sadržaja.';
$l['error_invalid_report_reason'] = 'Odabrani razlog nije ispravan.';
$l['error_comment_required'] = 'Zahtjeva se pisanje dodatnog komentara za odabrani razlog.';
