<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1813
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sun, 19 Apr 2020 13:40:45 +0000
// --------------------------------------------------------------------------------

$l['nav_search'] = 'Traži';
$l['nav_results'] = 'Rezultati';
$l['pages_last'] = 'zadnje';
$l['search'] = 'Traži';
$l['search_keyword'] = 'Traži po ključnoj riječi';
$l['search_username'] = 'Traži po korisničkom imenu';
$l['search_entire_post'] = 'pretraži postove';
$l['search_titles_only'] = 'pretraži samo naslove';
$l['match_username'] = 'sadrži korisničko ime';
$l['search_forums'] = 'Traži u forumu/ima';
$l['search_all_forums'] = 'Pretraži sve otvorene forume';
$l['search_options'] = 'Opcije pretrage';
$l['threads_at_least'] = 'Pronađi teme s najmanje';
$l['threads_at_most'] = 'Pronađi teme s najviše';
$l['find_anydate'] = 'Nađi postove s bilo kojim datumom slanja';
$l['find_yesterday'] = 'Nađi postove od juče';
$l['find_lastweek'] = 'Bađi postove od prije tjedan dana';
$l['find_2weeks'] = 'Nađi postove od prije 2 tjedna';
$l['find_month'] = 'Nađi postove od prije mjesec dana';
$l['find_3months'] = 'Nađi postove od prije 3 mjeseca';
$l['find_6months'] = 'Nađi postove od prije 6 mjeseci';
$l['find_year'] = 'Nađi postove od prošle godine';
$l['and_newer'] = 'i novije';
$l['and_older'] = 'i starije';
$l['sorting_options'] = 'Opcije slaganja';
$l['sort_lastpost'] = 'Složi rezultate po datumu zadnjeg posta';
$l['sort_author'] = 'Složi rezultate po autoru';
$l['sort_forum'] = 'Složi rezultate po forumu';
$l['sort_in'] = 'u';
$l['sort_asc'] = 'uzlazno';
$l['sort_desc'] = 'silazno';
$l['sort_order'] = 'redoslijed';
$l['asc'] = 'uzl';
$l['desc'] = 'sil';
$l['display_options'] = 'Opcije prikaza';
$l['show_results_as'] = 'Prikaži rezultate kao';
$l['show_results_threads'] = 'teme';
$l['show_results_posts'] = 'postove';
$l['search_results'] = 'Rezultati pretrage';
$l['post'] = 'Post';
$l['author'] = 'Autor';
$l['forum'] = 'Forum';
$l['replies'] = 'Odgovori';
$l['views'] = 'Pogledi';
$l['posted'] = 'Napisano';
$l['thread'] = 'Tema';
$l['lastpost'] = 'Zadnji post';
$l['post_thread'] = 'Tema:';
$l['post_subject'] = 'Post:';
$l['replies2'] = 'odgovora';
$l['selectall'] = 'Izaberi sve dodatne rezultate?';
$l['any_prefix'] = 'Potraži teme s bilo kojom prefiksom';
$l['no_prefix'] = 'Bez prefiksa';
$l['inline_thread_moderation'] = 'Inline Thread Moderation:';
$l['close_threads'] = 'Zatvori teme';
$l['open_threads'] = 'Otvori teme';
$l['stick_threads'] = 'Zalijepi teme';
$l['unstick_threads'] = 'Odlijepi teme';
$l['delete_threads'] = 'Obriši teme';
$l['move_threads'] = 'Premjesti teme';
$l['approve_threads'] = 'Dopusti teme';
$l['unapprove_threads'] = 'Odbij teme';
$l['inline_soft_delete_posts'] = 'Površno brisanje postova';
$l['inline_restore_posts'] = 'Vrati postove';
$l['inline_delete_posts'] = 'Trajno obriši postove';
$l['inline_merge_posts'] = 'Spoji postove';
$l['inline_split_posts'] = 'Rastavi postove';
$l['inline_approve_posts'] = 'Dopusti postove';
$l['inline_unapprove_posts'] = 'Odbij postove';
$l['inline_post_moderation'] = 'Inline Post Moderation:';
$l['inline_go'] = 'Idi';
$l['clear'] = 'Očisti';
$l['icon_dot'] = 'Sadrži vaše postove. ';
$l['icon_no_new'] = ' Nema novih postova';
$l['icon_new'] = ' Novi postovi';
$l['icon_hot'] = ' Vruća tema';
$l['icon_lock'] = ' Zaključana tema';
$l['attachment_count'] = 'Ova tema sadrži 1 prilog.';
$l['attachment_count_multiple'] = 'Ova tema sadrži {1} priloga.';
$l['goto_first_unread'] = 'Idi na prvi nepročitani post';
$l['page_selected'] = 'Svih <strong>{1}</strong> rezultata na ovoj stranici je odabrano';
$l['all_selected'] = 'Svi <strong>{1}</strong> rezultati ove pretrage su odabrani';
$l['select_all'] = 'Odaberi svih <strong>{1}</strong> rezultata u ovoj pretrazi.';
$l['clear_selection'] = 'Očisti odabir';
$l['search_user'] = 'Traži korisnika';
$l['results'] = 'rezultati';
$l['mod_options'] = 'Moderatorske opcije';
$l['display_all'] = 'Prikaži sve';
$l['display_only_approved'] = 'Prikaži samo dopušteno';
$l['display_only_unapproved'] = 'Prikaži samo nedopušteno';
$l['display_only_softdeleted'] = 'Prikaži samo površno obrisano';
$l['redirect_searchresults'] = 'Hvala vam, vaša pretraga je izvršena i sada ćete biti odvedeni na popis rezultata.';
$l['error_minsearchlength'] = 'Jedan ili više uvjeta pretrage je manji od najmanje moguće dužine.Najmanja dužina uvjeta je {1} znakova.<br /><br />Ako tražite frazu, označite je navodnicima. Na primjer "Brza smeđa lisica preskače lijenog psa".';
$l['error_nosearchresults'] = 'Žao nam je, ali nema pronađenih rezultata po zadanim kriterijima pretrage. Molimo vas da napišete druge kriterije i porušate ponovno.';
$l['error_no_search_support'] = 'Ovaj database engine ne podržava traženje.';
$l['error_nosearchterms'] = 'Niste unijeli niti jedan uvijet za pretraživanje. Najmanje morate unijeti neku riječ ili korisničko ime koje se traži.';
$l['error_searchflooding_1'] = 'Žao nam je, ali možete obaviti jednu pretragu svakih {1} sekundi. Molimo vas da pričekate još 1 sekundu prije ponovnog traženja.';
$l['error_searchflooding'] = 'Žao nam je, ali možete obaviti jednu pretragu svakih {1} sekundi. Molimo vas da pričekate još {2} sekundi prije ponovnog traženja.';
$l['error_invalidsearch'] = 'Neispravna pretraga je navedena. Molimo vas da se vratite natrag i pokušate ponovno.';
$l['soft_delete_threads'] = 'Površno obriši teme';
$l['restore_threads'] = 'Vrati teme';
$l['inline_move_posts'] = 'Premjesti postove';
$l['sort_views'] = 'Složi rezultate po broju pregleda';
$l['sort_replies'] = 'Složi rezultate po broju poruka';
$l['icon_close'] = 'Zatvorena tema.';
