<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:11:21 +0000
// --------------------------------------------------------------------------------

$l['nav_sendthread'] = 'Pošalji temu prijatelju';
$l['send_thread'] = 'Pošalji prijatelju';
$l['recipient'] = 'Primatelj:';
$l['recipient_note'] = 'Unesite prijateljev e-mail ovdje.';
$l['subject'] = 'Naslov:';
$l['message'] = 'Poruka:';
$l['error_nosubject'] = 'Trebate unijeti naslov kako biste poslali temu prijatelju.';
$l['error_nomessage'] = 'Trebate unijeti poruku kako biste poslali ovu temu prijatelju.';
