<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1813
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sun, 19 Apr 2020 13:43:51 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'Obriši anketu';
$l['close_thread'] = 'Zatvori temu';
$l['stick_thread'] = 'Zalijepi temu';
$l['author'] = 'Autor';
$l['message'] = 'Poruka';
$l['threaded'] = 'Threaded Mode';
$l['linear'] = 'Linear Mode';
$l['thread_modes'] = 'Thread Modes';
$l['next_oldest'] = 'Slijedeća starija';
$l['next_newest'] = 'Slijedeća novija';
$l['view_printable'] = 'Pogledaj verziju za ispis';
$l['send_thread'] = 'Pošalji ovu temu prijatelju';
$l['subscribe_thread'] = 'Pretplati se na ovu temu';
$l['unsubscribe_thread'] = 'Ukloni pretplatu na ovu temu';
$l['add_poll_to_thread'] = 'Dodaj anketu ovoj temu';
$l['moderation_options'] = 'Moderatorske opcije:';
$l['delayed_moderation'] = 'Delayed Moderation';
$l['thread_notes'] = 'Uredi / Pogledaj bilješke teme';
$l['open_close_thread'] = 'Otvori / zatvori temu';
$l['approve_thread'] = 'Dopusti temu';
$l['unapprove_thread'] = 'Odbij temu';
$l['soft_delete_thread'] = 'Površno obriši temu';
$l['restore_thread'] = 'Vrati temu';
$l['delete_thread'] = 'Trajno obriši temu';
$l['delete_posts'] = 'Obriši izabrane postove';
$l['move_thread'] = 'Premjesti / kopiraj temu';
$l['stick_unstick_thread'] = 'Zalijepi / odlijepi temu';
$l['split_thread'] = 'Razdvoji temu';
$l['merge_threads'] = 'Spoji teme';
$l['remove_redirects'] = 'Makni preusmjerenja';
$l['remove_subscriptions'] = 'Makni sve pretplate';
$l['poll'] = 'Anketa: ';
$l['show_results'] = 'Prikaži rezultate';
$l['edit_poll'] = 'Uredi anketu';
$l['public_note'] = '<b>Pažnja:</b> Ovo je javna anketa. Korisnici će moći vidjeti za što ste glasali.';
$l['total'] = 'Ukupno';
$l['vote'] = 'Glasaj';
$l['total_votes'] = '{1} glas(ova)';
$l['you_voted'] = '* Glasali ste za ovaj odabir';
$l['poll_closed'] = 'Ova anketa je zatvorena';
$l['poll_closes'] = 'Ova anketa će biti zatvorena na: {1}';
$l['already_voted'] = 'Ceć ste glasaliu ovoj anketi.';
$l['undo_vote'] = 'Obriši glas';
$l['quick_reply'] = 'Brzi odgovor';
$l['message_note'] = 'Napišite odgovor na ovu poruku ovdje.';
$l['signature'] = 'Potpis';
$l['email_notify'] = 'Obavijest e-mailom';
$l['disable_smilies'] = 'Isključi smajliće';
$l['post_reply'] = 'Odgovori';
$l['post_reply_img'] = 'Odgovori';
$l['new_reply'] = 'Odgovor';
$l['search_button'] = 'Traži';
$l['post_thread'] = 'Nova tema';
$l['preview_post'] = 'Pregled';
$l['rating_average'] = '{1} Glas (ova)- {2}  Prosječno';
$l['rate_thread'] = 'Ocijeni ovu temu:';
$l['thread_rating'] = 'Ocjena teme:';
$l['similar_threads'] = 'Vjerojatno slične teme...';
$l['thread'] = 'Tema';
$l['replies'] = 'Odgovora';
$l['views'] = 'Pogleda';
$l['lastpost'] = 'Zadnja poruka';
$l['messages_in_thread'] = 'Poruka u ovoj temi:';
$l['users_browsing_thread'] = 'Korisnika pretražuje ovu temu:';
$l['users_browsing_thread_guests'] = '{1} Gost(iju)';
$l['users_browsing_thread_invis'] = '{1} Nevidljivi(h)';
$l['users_browsing_thread_reading'] = 'Čita...';
$l['inline_soft_delete_posts'] = 'Površno obriši postove';
$l['inline_restore_posts'] = 'Vrati postove';
$l['inline_delete_posts'] = 'Trajno obrši postove';
$l['inline_merge_posts'] = 'Spoji postove';
$l['inline_split_posts'] = 'Razdvoji postove';
$l['inline_move_posts'] = 'Premjesti postove';
$l['inline_approve_posts'] = 'Dopusti postove';
$l['inline_unapprove_posts'] = 'Odbij postove';
$l['inline_post_moderation'] = 'Inline Post Moderation:';
$l['inline_go'] = 'Idi';
$l['clear'] = 'Očisti';
$l['thread_closed'] = 'Tema zatvorena';
$l['no_subject'] = 'Bez naslova';
$l['error_nonextnewest'] = 'Nema novijih tema od one na kojoj ste sada bili.';
$l['error_nonextoldest'] = 'Nema starijih tema od one na kojoj ste sada bili.';
$l['quickreply_multiquote_selected'] = 'Izabrali ste jedan ili više postova za citiranje.';
$l['quickreply_multiquote_now'] = 'Citiraj ove postove sada';
$l['or'] = 'ili';
$l['quickreply_multiquote_deselect'] = 'neodaberi ih';
$l['search_thread'] = 'Traži temu';
$l['enter_keywords'] = 'Unesite ključne riječi';
$l['view_thread_notes'] = 'Bilješke teme';
$l['view_all_notes'] = 'Pogledaj sve bilješke';
$l['save_changes'] = 'Spremi promjene';
$l['cancel_edit'] = 'Odustani od uređivanja';
$l['quick_edit_update_error'] = 'Dogodila se greška kod uređivanja vašega odgovora:';
$l['quick_reply_post_error'] = 'Dogodila se greška kod pisanja vašega odgovora:';
$l['quick_delete_error'] = 'Dogodila se greška kod brisanja vašega odgovora:';
$l['quick_delete_success'] = 'Vaš post je uspješno izbrisan.';
$l['quick_delete_thread_success'] = 'Tema je uspješno izbrisana.';
$l['quick_restore_error'] = 'Dogodila se greška kod vraćanja vašega odgovora:';
$l['quick_restore_success'] = 'Post je uspješno vraćen.';
$l['no_voting_permission'] = 'Nemate dopuštenje glasati u ovoj anketi.';
$l['post_deleted_error'] = 'Ne možete izvršiti ovu akciju na izbrisanu poruku.';
