<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:08:32 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = 'Statistika foruma';
$l['stats_disabled'] = 'Ne možete vidjeti statistike foruma jer nisu odobrene od administratora.';
$l['board_stats'] = 'Statistika foruma';
$l['none'] = 'Nitko';
$l['totals'] = 'Ukupno';
$l['averages'] = 'Prosječno';
$l['posts'] = 'Poruke:';
$l['threads'] = 'Teme:';
$l['members'] = 'Članovi:';
$l['ppd'] = 'Poruke po danu:';
$l['tpd'] = 'Teme po danu:';
$l['mpd'] = 'Članova po danu';
$l['ppm'] = 'Poruka po članu:';
$l['tpm'] = 'Tema po članu:';
$l['rpt'] = 'Odgovora po temi:';
$l['no_posts'] = 'Ne';
$l['general'] = 'Opće';
$l['newest_member'] = 'Najnoviji član:';
$l['members_posted'] = 'Članovi koji su pisali:';
$l['todays_top_poster'] = 'Današnji top poster: <b>{1}</b> (<b>{2}</b> postova)';
$l['popular_forum'] = 'Najpopularniji forum: <b>{1}</b> (<b>{2}</b> poruka, <b>{3}</b> tema)';
$l['most_popular'] = 'Najpopularnije...';
$l['most_replied_threads'] = 'Teme s najviše odgovora';
$l['most_viewed_threads'] = 'Najgledanije teme';
$l['not_enough_info_stats'] = 'Žao nam je, ali nema dovoljno informacija za kreiranje statistike foruma. Prije nego statistika može biti napravljena, morate imati barem 1 člana i 1 temu.';
$l['replies'] = 'odgovora';
$l['views'] = 'pogleda';
$l['top_referrer'] = 'Top preporučitelj: <strong>{1}</strong> (<strong>{2}</strong> preporuka)';
