<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:08:04 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '180';
$l['ucp_nav_menu'] = 'Menu';
$l['ucp_nav_messenger'] = 'Poruke';
$l['ucp_nav_compose'] = 'Nova';
$l['ucp_nav_tracking'] = 'Tracking';
$l['ucp_nav_edit_folders'] = 'Uredi mape';
$l['ucp_nav_profile'] = 'Vaš profil';
$l['ucp_nav_edit_profile'] = 'Uredi profil';
$l['ucp_nav_edit_options'] = 'Uredi opcije';
$l['ucp_nav_change_email'] = 'Promijeni e-mail';
$l['ucp_nav_change_pass'] = 'Promijeni lozinku';
$l['ucp_nav_change_username'] = 'Promijeni korisničko ime';
$l['ucp_nav_edit_sig'] = 'Promijeni potpis';
$l['ucp_nav_change_avatar'] = 'Promijeni avatar';
$l['ucp_nav_misc'] = 'Ostalo';
$l['ucp_nav_editlists'] = 'Popis prijatelja/ignoriranih';
$l['ucp_nav_favorite_threads'] = 'Najdraže teme';
$l['ucp_nav_subscribed_threads'] = 'Pretplaćene teme';
$l['ucp_nav_forum_subscriptions'] = 'Pretplaćeni forumi';
$l['ucp_nav_drafts'] = 'Spremjeni nacrti';
$l['ucp_nav_drafts_active'] = '<strong>Spremljeni nacrti ({1})</strong>';
$l['ucp_nav_notepad'] = 'Vlastiti blok';
$l['ucp_nav_view_profile'] = 'Pogledaj profil';
$l['ucp_nav_home'] = 'Početna korisničke ploče';
$l['ucp_nav_usergroups'] = 'Članstva u grupama';
$l['ucp_nav_attachments'] = 'Upravljaj prilozima';
