<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:07:55 +0000
// --------------------------------------------------------------------------------

$l['nav_profile'] = 'Profil od {1}';
$l['nav_warning_log'] = 'Popis upozorenja';
$l['nav_add_warning'] = 'Upozori korisnika';
$l['nav_view_warning'] = 'Detalji upozorenja';
$l['warning_for_post'] = '.. Post:';
$l['already_expired'] = 'Istječe';
$l['details_username'] = 'Korisničko ime';
$l['warning_active'] = 'Aktivno';
$l['warning_revoked'] = 'Odbačeno';
$l['warning_log'] = 'Popis upozorenja';
$l['warning'] = 'Upozorenje';
$l['issued_by'] = 'Uzrokovano od';
$l['date_issued'] = 'Datum uzroka';
$l['expiry_date'] = 'Istječe';
$l['active_warnings'] = 'Aktivna upozorenja';
$l['expired_warnings'] = 'Istečena upozorenja';
$l['warning_points'] = '({1} bodova)';
$l['no_warnings'] = 'Ovaj korisnik nije primio niti jedno upozorenje ili su mu sva izbrisana.';
$l['warn_user'] = 'Upozori korisnika';
$l['post'] = 'Poruka:';
$l['warning_note'] = 'Administrativne bilješke:';
$l['details_warning_note'] = 'Administrativne bilješke';
$l['warning_type'] = 'Tip upozorenja:';
$l['custom'] = 'Vlastiti razlog';
$l['reason'] = 'Razlog:';
$l['points'] = 'Bodovi:';
$l['details_reason'] = 'Razlog';
$l['warn_user_desc'] = 'Ovdje možete povisiti količinu upozorenja ovoga korisnika ako je prekršio jedno ili više pravila.';
$l['send_pm'] = 'Obavijesti korisnika:';
$l['send_user_warning_pm'] = 'Pošalji korisniku privatnu poruku obaviještavajući ga o upotorenuju.';
$l['send_pm_subject'] = 'Naziv:';
$l['warning_pm_subject'] = 'Primili ste upozorenje.';
$l['send_pm_message'] = 'Poruka:';
$l['warning_pm_message'] = 'Dragi {1}

Primili ste upozorenje od člana osoblja {2}.
--

--';
$l['send_pm_options'] = 'Opcije:';
$l['send_pm_options_anonymous'] = '<strong>Anonimna PP</strong>: Pošalji ovu poruku kao anonimni korisnik.';
$l['expiration_never'] = 'trajno';
$l['expiration_hours'] = 'sati';
$l['expiration_days'] = 'dana';
$l['expiration_weeks'] = 'tjedana';
$l['expiration_months'] = 'mjeseci';
$l['redirect_warned_banned'] = '<br /><br />Također, korisnik je premješten u {1} grupu {2}.';
$l['redirect_warned_suspended'] = '<br /><br />Privilegije ovoga korsinika da piše na forumu su maknute {1}.';
$l['redirect_warned_moderate'] = '<br /><br />Sve poruke ovoga korisnika će sada biti moderiarane {1}.';
$l['redirect_warned_pmerror'] = '<br /><br />Molimo pripazite da PP neće biti poslana.';
$l['redirect_warned'] = 'Razina upozorenja od {1} je povećšana na {2}%. {3}<br /><br /> Sada ćete biti vraćeni odakle ste došli.';
$l['error_warning_system_disabled'] = 'Ne možete koristiti sustav upozorenja jer ga administrator nije odobrio.';
$l['error_cant_warn_group'] = 'Nemate dopuštenja da upozoravate korisnike ove grupe.';
$l['error_invalid_user'] = 'Izabrani korisnik ne postoji.';
$l['details'] = 'Detalji';
$l['view'] = 'Pogledaj';
$l['current_warning_level'] = 'Trenutna razina upozorenja: <strong>{1}%</strong> ({2}/{3})';
$l['warning_details'] = 'Detalji upozorenja';
$l['revoke_warning'] = 'Makni ovo upozorenje';
$l['revoke_warning_desc'] = 'Da biste maknuli ovo upozorenja, molimo vas da unesete razlog ispod. Ovo neće maknuti nikakve banove ili suspenzije uzrokovane ovim upozorenjem.';
$l['warning_is_revoked'] = 'Ovo upozorenje je maknuto';
$l['revoked_by'] = 'Maknuo';
$l['date_revoked'] = 'Datum micanja';
$l['warning_already_revoked'] = 'Ovo upozorenje je već maknuto.';
$l['no_revoke_reason'] = 'Niste unijeli razlog zašto želite maknuti ovo upozorenje.';
$l['redirect_warning_revoked'] = 'Ovo upozorenje je uspješno maknuto i bodovi korisnika sniženi.<br /><br />Sada ćete biti vraćeni na upozorenja.';
$l['result'] = 'Rezultat:';
$l['result_banned'] = 'Korisnik će biti premješten u banranu grupu ({1}) {2}';
$l['result_suspended'] = 'Privilegije pisanja će biti maknute {1}';
$l['result_moderated'] = 'Poruke će biti moderirane {1}';
$l['result_period'] = 'za {1} {2}';
$l['result_period_perm'] = 'trajno';
$l['hour_or_hours'] = 'Sat(i)';
$l['day_or_days'] = 'Dan(a)';
$l['week_or_weeks'] = 'Tjedan(a)';
$l['month_or_months'] = 'Mjesec(i)';
$l['expires'] = 'Istječe:';
$l['new_warning_level'] = 'Nova razina upozorenja:';
$l['error_cant_warn_user'] = 'Nemate dopuštenje da upozorite ovoga korisnika.';
$l['existing_post_warnings'] = 'Postojeća upozorenja na ovoj poruci';
