<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:07:47 +0000
// --------------------------------------------------------------------------------

$l['no_new_subject'] = 'Niste unijeli novi naziv.';
$l['post_moderation'] = 'Vaš post se sada moderira.';
$l['thread_moderation'] = 'Vaša tema se sada moderira.';
$l['post_doesnt_exist'] = 'Navedeni post ne postoji.';
$l['thread_doesnt_exist'] = 'Navedena tema ne postoji.';
$l['thread_closed_edit_subjects'] = 'Ova tema je zatvorena, te ne možete uređivati nazive.';
$l['no_permission_edit_subject'] = 'Nemate dopuštenja za uređivanje naziva ove teme.';
$l['thread_closed_edit_message'] = 'Ova tema je zatvorena i ne možete uređivati poruke unutar nje.';
$l['no_permission_edit_post'] = 'Nemate dopuštenja da uredite ovu poruku.';
$l['edit_time_limit'] = 'Možete uređivati poruke samo {1} minuta nakon što su napisane.';
$l['postbit_edited'] = 'Ovu poruku je zadnje uređivana: {1} od ';
$l['postbit_editreason'] = 'Razlog uređivanja';
$l['save_changes'] = 'Spremi promjene';
$l['cancel_edit'] = 'Odustani';
$l['answer_valid_not_exists'] = 'Pitanje na koje pokušavate odgovoriti ne postoji.';
$l['captcha_not_exists'] = 'Provjera slikom koju pokušavate osvježiti ne postoji.';
$l['captcha_valid_not_exists'] = 'Provjera slikom koju pokušavate označiti ne postoji.';
$l['captcha_does_not_match'] = 'Kod za provjeru slikom koji ste unijeli nije ispravan. Molimo vas da ga unesete točnoga onakoga kakvoga ga vidite na slici.';
$l['captcha_matches'] = 'Kod za provjeru slikom koji ste unijeli nije ispravan.';
$l['answer_does_not_match'] = 'Odgovor koji ste unijeli nije točan.';
$l['banned_username'] = 'Korisničko ime koje ste unijeli nije dopušteno od strane administratora.';
$l['banned_characters_username'] = 'Vaše korisničko ime sadrži jedan ili više neispravnih znakova.';
$l['complex_password_fails'] = 'Lozinka zahtijava veliko slovo, malo slovo i broj';
$l['username_taken'] = '{1} je već registrirano od drugog člana';
$l['username_available'] = '{1} je dostupno';
$l['invalid_username'] = '{1} je korisničko ime registriranog člana';
$l['valid_username'] = '{1} je ispravni preporučitelj.';
$l['buddylist_error'] = 'Izgleda da nemate prijatelja na vašem popisu prijatelja. Polimo vas da dodate neke prije korištenja ovoga.';
$l['close'] = 'Zatvori';
$l['select_buddies'] = 'Odaberi prijatelje';
$l['select_buddies_desc'] = 'Za dodavanje jednoga ili više prijatelja kao primatelje, odaberite ih ispod i kliknite U redu.';
$l['selected_recipients'] = 'Odabrani primatelji';
$l['ok'] = 'U redu';
$l['cancel'] = 'Odustani';
$l['online'] = 'Online';
$l['offline'] = 'Offline';
$l['edited_post'] = 'Uređeni post';
$l['usergroup'] = 'Korisnička grupa';
