<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 11:30:35 +0000
// --------------------------------------------------------------------------------

$l['contact'] = 'Kontaktiraj nas';
$l['contact_no_message'] = 'Niste unijeli poruku za slanje.';
$l['contact_no_subject'] = 'Trebate unijeti naslov.';
$l['contact_no_email'] = 'Morate unijeti ispravnu e-mail adresu.';
$l['contact_success_message'] = 'Vaša poruka je uspješno poslana Administratoru.';
$l['contact_subject'] = 'Naslov';
$l['contact_subject_desc'] = 'Ukratko opišite temu vaše poruke.';
$l['contact_message'] = 'Poruka';
$l['contact_message_desc'] = 'Ovdje detaljno opišite problem.';
$l['contact_email'] = 'E-mail';
$l['contact_email_desc'] = 'Unesite svoju e-mail adresu kako bismo vas mogli kontaktirati.';
$l['contact_send'] = 'Pošalji';
$l['subject_too_long'] = 'Naslov je predug. Molimo unesite kraći naslov od {1} znakova (trenutno {2}).';
$l['message_too_short'] = 'Poruka je prekratka. Molimo unesite poruku dužu od {1} znakova (trenutno {2}).';
$l['message_too_long'] = 'Poruka je preduga. Molimo unesite puruku kraću od {1} znakova (trenutno {2}).';
$l['error_stop_forum_spam_spammer'] = 'Žao nam je, {1} odgovara poznatom spammeru, te je zbog toga je vaša poruka blokirana.';
$l['error_stop_forum_spam_fetching'] = 'Žao nam je, ne može se pristupiti bazi poznatih spammera (zbog provjere). Najvjerojatnije se bazi podataka ne može se pristupiti. Molimo pokušajte ponovno kasnije.';
