<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 11:31:22 +0000
// --------------------------------------------------------------------------------

$l['eventdata_missing_name'] = 'Nedostaje naziv događaja. Molimo vas unesite naziv.';
$l['eventdata_missing_description'] = 'Nedostaje opis događaja. Molimo vas unesite opis.';
$l['eventdata_invalid_start_date'] = 'Datum početka koji ste unijeli nije ispravan. Molimo unesite ispravan datum događaja. Provjerite jeste li odabrali dan, mjesec i godinu kao i je li dan koji ste unijeli ispravan za određeni mjesec.';
$l['eventdata_invalid_start_year'] = 'Događaj može biti napravljen samo za slijedećih 5 godina. Molimo odaberite razumnu godinu s popisa.';
$l['eventdata_invalid_start_month'] = 'Mjesec početka koji ste unijeli nije ispravan mjesec. Molimo unesite ispravan mjesec početka.';
$l['eventdata_invalid_end_date'] = 'Dan kraja događaja koji ste unijeli nije ispravan. Provjerite jeste li odabrali dan, mjesec i godinu kao i je li dan koji ste unijeli ispravan za određeni mjesec.';
$l['eventdata_invalid_end_year'] = 'Događaji mogu biti napravljeni samo za slijedećih 5 godina. Molimo odaberite razumnu godinu završetka s popisa.';
$l['eventdata_invalid_end_month'] = 'Mjesec završetka koji ste unijeli nije ispravan mjesec. Molimo unesite ispravan mjesec završetka.';
$l['eventdata_invalid_end_day'] = 'Dan završetka koji ste unijeli nije ispravan. Najvjerojatnije je dan koji ste izabrali veći od broja dana u određenom mjesecu.';
$l['eventdata_cant_specify_one_time'] = 'Ako određujete vrijeme početka događaja, trebate unijeti i vrijeme završetka događaja.';
$l['eventdata_start_time_invalid'] = 'Vrijeme početka koje ste unijeli nije ispravno. Ispravni primjeri su 12am, 12:01am, 00:01.';
$l['eventdata_end_time_invalid'] = 'Vrijeme završetka koje ste unijeli nije ispravno. Ispravni primjeri su 12am, 12:01am, 00:01.';
$l['eventdata_invalid_timezone'] = 'Vremenska zona koju ste izabrali za ovaj događaj nije ispravna.';
$l['eventdata_end_in_past'] = 'Datum ili vrijeme završetka vašega događaja je ranije od datuma ili vremena početka.';
$l['eventdata_only_ranged_events_repeat'] = 'Samo se događaji u opsegu (događaji sa datumom početka i završetka) mogu ponavljati.';
$l['eventdata_invalid_repeat_day_interval'] = 'Niste unijeli ispravan dan za ponavljanje intervala.';
$l['eventdata_invalid_repeat_week_interval'] = 'Niste unijeli ispravan tjedan za ponavljanje intervala.';
$l['eventdata_invalid_repeat_weekly_days'] = 'Niste izabrali niti jedan radni dan na koji bi se pojavio ovaj događaj.';
$l['eventdata_invalid_repeat_month_interval'] = 'Niste unijeli ispravan mjesec za ponavljanje intervala.';
$l['eventdata_invalid_repeat_year_interval'] = 'Niste unijeli ispravnu godinu za ponavljanje intervala.';
$l['eventdata_event_wont_occur'] = 'Koristeći vremena početka i završetka zajedno sa postavkama ponavljanja događaja, ovaj događaj se neće pojaviti.';
$l['eventdata_no_permission_private_event'] = 'Nemate dozvolu za slanje privatnih događaja.';
