<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1813
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sun, 19 Apr 2020 13:18:25 +0000
// --------------------------------------------------------------------------------

$l['post_thread'] = 'Nova tema';
$l['moderated_by'] = 'Moderatori foruma:';
$l['nothreads'] = 'Žao nam je, ali trenutno nema tema u ovom forumu sa traženim datumom.';
$l['search_forum'] = 'Pretraži ovaj forum:';
$l['thread'] = 'Tema';
$l['author'] = 'Autor';
$l['replies'] = 'Odgovora';
$l['views'] = 'Pregleda';
$l['lastpost'] = 'Posljednja Poruka';
$l['rating'] = 'Ocjena';
$l['prefix'] = 'Prefiks:';
$l['prefix_all'] = 'Prefiks: bilo koji/bez prefiksa';
$l['prefix_any'] = 'Prefiks: bilo koji prefiks';
$l['prefix_none'] = 'Prefiks: bez prefiksa';
$l['markforum_read'] = 'Označi ovaj forum pročitanim';
$l['subscribe_forum'] = 'Prati ovaj forum';
$l['unsubscribe_forum'] = 'Prestani pratiti ovaj forum';
$l['clear_stored_password'] = 'Izbriši spremljene lozinke foruma';
$l['sort_by_subject'] = 'Složi po: Naslovu';
$l['sort_by_lastpost'] = 'Složi po: Posljednjoj poruci';
$l['sort_by_starter'] = 'Složi po: Autoru';
$l['sort_by_started'] = 'Složi po: Vremenu poruke';
$l['sort_by_rating'] = 'Složi po: Ocjeni';
$l['sort_by_replies'] = 'Složi po: Odgovorima';
$l['sort_by_views'] = 'Složi po: Pregledima';
$l['sort_order_asc'] = 'Redoslijed: Uzlazno';
$l['sort_order_desc'] = 'Redoslijed: Silazno';
$l['datelimit_1day'] = 'Od: Danas';
$l['datelimit_5days'] = 'Od: Prije 5 dana';
$l['datelimit_10days'] = 'Od: Prije 10 dana';
$l['datelimit_20days'] = 'Od: Prije 20 dana';
$l['datelimit_50days'] = 'Od: Prije 50 dana';
$l['datelimit_75days'] = 'Od: Prije 75 dana';
$l['datelimit_100days'] = 'Od: Prije 100 dana';
$l['datelimit_lastyear'] = 'Od: Posljednje Godine';
$l['datelimit_beginning'] = 'Od: Početka';
$l['new_thread'] = 'Nova Tema';
$l['new_hot_thread'] = 'Vruća tema (novo)';
$l['posts_by_you'] = 'Sadrži vaše poruke';
$l['no_new_thread'] = 'Nema novih tema';
$l['hot_thread'] = 'Vruća tema (nema novih poruka)';
$l['locked_thread'] = 'Zaključana tema';
$l['goto_first_unread'] = 'Idi na prvu nepročitanu poruku';
$l['pages'] = 'Stranica:';
$l['pages_last'] = 'zadnja';
$l['users_browsing_forum'] = 'Korisnika pregleda ovaj forum:';
$l['users_browsing_forum_guests'] = '{1} Gost(iju)';
$l['users_browsing_forum_invis'] = '{1} Skrivenih Korisnik(a)';
$l['delayed_moderation'] = 'Zakašnjelo  uređivanje';
$l['inline_thread_moderation'] = 'Linijsko uređivanje tema:';
$l['close_threads'] = 'Zatvori teme';
$l['open_threads'] = 'Otvori teme';
$l['stick_threads'] = 'Zalijepi teme';
$l['unstick_threads'] = 'Odlijepi teme';
$l['soft_delete_threads'] = 'Privremeno izbriši teme';
$l['restore_threads'] = 'Vrati teme';
$l['delete_threads'] = 'Trajno izbriši teme';
$l['move_threads'] = 'Premjesti teme';
$l['approve_threads'] = 'Odobri teme';
$l['unapprove_threads'] = 'Odbij teme';
$l['inline_go'] = 'Idi';
$l['clear'] = 'Očisti';
$l['sub_forums_in'] = 'Forumi u \'{1}\'';
$l['forum_rules'] = '{1} - Pravila';
$l['subforums'] = '<strong>Pod forumi:</strong>';
$l['asc'] = 'uzlazno';
$l['desc'] = 'silazno';
$l['forum_announcements'] = 'Forumske obavijseti';
$l['sticky_threads'] = 'Važne teme';
$l['normal_threads'] = 'Normalne teme';
$l['icon_dot'] = 'Sadrži vaše poruke. ';
$l['icon_no_new'] = 'Nema novih poruka.';
$l['icon_new'] = 'Nove poruke.';
$l['icon_hot'] = ' Vruća tema.';
$l['icon_lock'] = ' Zaključana tema.';
$l['attachment_count'] = 'Ova tema sadrži 1 prilog.';
$l['attachment_count_multiple'] = 'Ova tema sadrži {1} priloga.';
$l['rss_discovery_forum'] = 'Najnovije teme u {1}';
$l['forum_unapproved_posts_count'] = 'Trenutno {1} poruka u ovom forumu čeka odobrenje.';
$l['forum_unapproved_post_count'] = 'Trenutno 1 poruka u ovom forumu čeka odobrenje.';
$l['forum_unapproved_threads_count'] = 'Trenutno {1} tema u ovom forumu čeka odobrenje.';
$l['forum_unapproved_thread_count'] = 'Trenutno 1 tema u ovom forumu čeka odobrenje.';
$l['thread_unapproved_posts_count'] = 'Trenutno {1} poruka u ovoj temi čeka odobrenje.';
$l['thread_unapproved_post_count'] = 'Trenutno 1 poruka u ovoj temi čeka odobrenje.';
$l['page_selected'] = 'Svih <strong>{1}</strong> tema na ovoj stranici je izabrano.';
$l['all_selected'] = 'Svih <strong>{1}</strong> tema u ovom forumu je izabrano.';
$l['select_all'] = 'Odabir svih <strong>{1}</strong> tema u ovom forumu.';
$l['clear_selection'] = 'Poništi odabir.';
$l['error_containsnoforums'] = 'Žao nam je, ali forum koji trenutno pregledavate ne sadrži nikakve podforume.';
$l['inline_edit_description'] = '(Klikni i drži za uređivanje)';
$l['nopermission'] = 'Žao nam je, ali nemate dopuštenje da biste vidjeli teme u ovom forumu';
$l['deleted_thread'] = 'Obrisana tema';
$l['closed_thread'] = 'Zatvorena Tema';
$l['icon_close'] = 'Zatvorena Tema';
