<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 11:41:53 +0000
// --------------------------------------------------------------------------------

$l['error_no_connection'] = 'Došlo je do greške u uspostavljanju veze preko servera: ';
$l['error_no_message'] = 'Poruka nije bila unesena.';
$l['error_no_subject'] = 'Naslov nije bio unesen';
$l['error_no_recipient'] = 'Primatelj nije bio unesen.';
$l['error_not_sent'] = 'Došlo je do greške tokom pokušaja slanja e-maila preko php mail funkcije.';
$l['error_status_missmatch'] = 'Stanje sa servera se ne slaže sa očekivanim rezultatom, vraća: ';
$l['error_data_not_sent'] = 'Ovi podaci ne mogu biti poslani serveru: ';
$l['error_occurred'] = 'Jedna ili više grešaka se pojavila. Molimo ispravite slijedeće greške prije nastavka.<br />';
