<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 11:44:29 +0000
// --------------------------------------------------------------------------------

$l['nav_group_management'] = '{1} Uređivanje grupe';
$l['nav_join_requests'] = 'Zahtjevi za pristup';
$l['nav_group_memberships'] = 'Članstvo u grupi';
$l['not_leader_of_this_group'] = 'Žao nam je, ali vi niste voditelj ove grupe.';
$l['invalid_group'] = 'Ova korisnička grupa ne postoji.';
$l['pending_requests'] = 'Nerješeni zahtijevi za pristup';
$l['num_requests_pending'] = 'Trenutno ima <strong>{1}</strong> ne rješenih zahtijeva za pristup ovoj grupi.';
$l['group_management'] = 'Upravljanje grupom';
$l['members_of'] = 'Članovi u "{1}"';
$l['user_name'] = 'Korisničko ime';
$l['contact'] = 'Kontakt';
$l['reg_date'] = 'Registriran';
$l['post_count'] = 'Poruka';
$l['remove_selected'] = 'Ukloni izabrane korisnike iz grupe';
$l['add_member'] = 'Dodaj člana u "{1}"';
$l['add_member_submit'] = 'Dodaj člana u grupu';
$l['invite_member'] = 'Pozovi člana u "{1}"';
$l['invite_member_submit'] = 'Pozovi člana u grupu';
$l['join_requests'] = 'Zahtijevi za pristup';
$l['join_requests_title'] = 'Zahtijevi za pristup u "{1}"';
$l['leader'] = '(Voditelj)';
$l['reason'] = 'Razlog';
$l['accept'] = 'Prihvati';
$l['ignore'] = 'Ignoriraj';
$l['decline'] = 'Odbij';
$l['action_requests'] = 'Izvedi radnje';
$l['join_requests_moderated'] = 'Zahtjevi za pristup su odobreni.<br />Sada ćete biti vraćeni na popis zahtjeva.';
$l['no_requests'] = 'Trenutno nema neriješenih zahtijeva za pristup za ovoj grupi.';
$l['no_users'] = 'Ne postoje korisnici u ovoj grupi.';
$l['user_added'] = 'Korisnik je dodan u korisničku grupu.';
$l['users_removed'] = 'Odabrani korisnik je obrisan iz korisničke grupe.';
$l['group_no_members'] = 'Trenutno nema članova u ovoj grupi.<br />Za povratak na stranicu za uređivanje grupe, kliknite <a href="usercp.php?action=usergroups">ovdje</a>.';
$l['group_public_moderated'] = 'Korisnička grupa je javna korisnička grupa kojoj se svi mogu pridružiti.  Svi zahtijevi za pristup moraju biti odobreni od voditelja grupe.';
$l['group_public_not_moderated'] = 'Ova korisnička grupa je javna i svi joj se slobodno mogu pridružiti.';
$l['group_public_invite'] = 'Ova korisnička grupa je javna grupa koja zahtijeva pozivnicu od voditelja grupe za pridruživanje grupi.';
$l['group_private'] = 'Ova korisnička grupa je privatna grupa.  Samo korisnici koje doda voditelj grupe mogu biti dio ove grupe.';
$l['group_default'] = 'Ova korisnička grupa je središnja korisnička grupa.';
$l['group_leaders'] = 'Voditelji grupa';
$l['search_user'] = 'Traži korisnika';
$l['no_users_selected'] = 'Žao nam je, ali izgleda da niti jedan korisnik nije izabran za uklanjanje.<br />Molimo idite natrag i odaberite korisnike koje želite ukloniti iz ove grupe.';
$l['error_alreadyingroup'] = 'Odabrani korisnik je već dio ove korisničke grupe.';
$l['error_alreadyinvited'] = 'Odabrani korisnik je već pozvan.';
$l['user_invited'] = 'Korisnik je pozvan da se pridruži korisničkoj grupi.';
$l['invite_pm_subject'] = 'Pozvani ste da se pridružite grupi "{1}"';
$l['invite_pm_message'] = 'Dobili ste pozivnicu da se pridružite korisničkoj grupi "{1}".

Za pridruživanje, molimo idite do vaše stranice [url={2}/usercp.php?action=usergroups]članstvo u grupi[/url] i kliknite \'Prihvati poziv\'.

Ovaj poziv ne ističe.';
$l['invite_pm_message_expires'] = 'Dobili ste pozivnicu da se pridružite korisničkoj grupi "{1}".

Za pridruživanje, molimo idite do vaše stranice [url={2}/usercp.php?action=usergroups]članstvo u grupi[/url] i kliknite \'Prihvati poziv\'.

Ovaj poziv ističe za {3} dana od sada.';
