<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1813
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sun, 19 Apr 2020 13:33:18 +0000
// --------------------------------------------------------------------------------

$l['nav_register'] = 'Registracija';
$l['nav_activate'] = 'Aktiviraj';
$l['nav_resendactivation'] = 'Ponovno slanje aktivacionog e-maila';
$l['nav_lostpw'] = 'Povratak izgubljene lozinke';
$l['nav_resetpassword'] = 'Ponovno postavi lozinku';
$l['nav_login'] = 'Prijava';
$l['nav_emailuser'] = 'Pošalji e-mail korisniku';
$l['nav_profile'] = 'Profil od {1}';
$l['tpp_option'] = 'Prikaži {1} tema po stranici';
$l['ppp_option'] = 'Prikaži {1} poruka po stranici';
$l['account_activation'] = 'Aktivacija računa';
$l['activate_account'] = 'Aktiviraj račun';
$l['activation_code'] = 'Aktivacjski kod:';
$l['email_user'] = 'Pošalji {1} e-mail';
$l['email_subject'] = 'Naslov e-maila';
$l['email_message'] = 'E-mail poruka';
$l['send_email'] = 'Pošalji e-mail';
$l['error_hideemail'] = 'Primatelj je izabrao sakrivanje svoje e-mail adrese te mu zbog toga ne možete poslati e-mail.';
$l['error_no_email_subject'] = 'Trebate unijeti naslov za vaš emai';
$l['error_no_email_message'] = 'Trebate unijeti poruku za vaš email';
$l['login'] = 'Prijava';
$l['pw_note'] = 'Molimo znajte da je lozinka osjetljiva na velika i mala slova.';
$l['lostpw_note'] = 'Zaboravili ste lozinku?';
$l['lost_pw'] = 'Izgubljena lozinka računa';
$l['lost_pw_form'] = 'Obrazac za povratak izgubljene lozinke';
$l['email_address'] = 'E-mail Adresa:';
$l['request_user_pass'] = 'Traži akreditive prijave';
$l['profile'] = 'Profil od {1}';
$l['registration_date'] = 'Datum registracije:';
$l['date_of_birth'] = 'Datum rođenja:';
$l['birthdayhidden'] = 'Skriven';
$l['birthday'] = 'Rođendan:';
$l['local_time'] = 'Mjesno Vrijeme:';
$l['local_time_format'] = '{1} u {2}';
$l['users_forum_info'] = '{1} forum info';
$l['joined'] = 'Pridružen:';
$l['lastvisit'] = 'Posljednja posjeta:';
$l['total_posts'] = 'Ukupno poruka:';
$l['ppd_percent_total'] = '{1} poruka dnevno | {2} posto od ukupnih poruka';
$l['total_threads'] = 'Ukupno tema:';
$l['tpd_percent_total'] = '{1} tema po danu | {2} posto od ukupnih tema';
$l['find_posts'] = 'Pronađi sve poruke';
$l['find_threads'] = 'Pronađi sve teme';
$l['members_referred'] = 'Preporučenih članova:';
$l['rating'] = 'Ocjena:';
$l['users_contact_details'] = '{1} Pojedinosti kontakta';
$l['homepage'] = 'Početna stranica:';
$l['pm'] = 'Privatna poruka:';
$l['send_pm'] = 'Pošalji privatnu poruku za {1}.';
$l['icq_number'] = 'ICQ broj:';
$l['aim_screenname'] = 'AIM Screen Ime:';
$l['yahoo_id'] = 'Yahoo ID:';
$l['skype_id'] = 'Skype ID:';
$l['google_id'] = 'Google Talk ID:';
$l['avatar'] = 'Avatar:';
$l['warning_level'] = 'Nivo upozorenja:';
$l['warn'] = 'Upozorenja';
$l['away_note'] = '{1} je trenutno odsutan.';
$l['away_reason'] = 'Razlog:';
$l['away_since'] = 'Odsutan od:';
$l['away_returns'] = 'Povratak:';
$l['away_no_reason'] = 'Nije određeno.';
$l['ban_note'] = 'Ovaj račun na forumu je trenutno baniran.';
$l['ban_by'] = 'Baniran od:';
$l['ban_length'] = 'Dužina bana';
$l['users_additional_info'] = 'Dodatni podaci o {1}';
$l['email'] = 'E-mail:';
$l['send_user_email'] = 'Pošalji e-mail za {1}.';
$l['users_signature'] = '{1} potpis';
$l['agreement'] = 'Registration Agreement';
$l['agreement_1'] = 'Whilst we attempt to edit or remove any messages containing inappropriate, sexually orientated, abusive, hateful, slanderous, or threatening material that could be considered invasive of a person\'s privacy, or which otherwise violate any kind of law, it is impossible for us to review every message posted on this discussion system. For this reason you acknowledge that all messages posted on this discussion system express the views and opinions of the original message author and not necessarily the views of this bulletin board. Therefore we take no responsibility and cannot be held liable for any messages posted. We do not vouch for or warrant the accuracy and completeness of every message.';
$l['agreement_2'] = 'By registering on this discussion system you agree that you will not post any material which is knowingly false, inaccurate, abusive, hateful, harassing, sexually orientated, threatening or invasive of a person\'s privacy, or any other material which may violate any applicable laws.';
$l['agreement_3'] = 'Failure to comply with these rules may result in the termination of your account, account suspension, or permanent ban of access to these forums. Your IP Address is recorded with each post you make on this discussion system and is retrievable by the forum staff if need-be. You agree that we have the ability and right to remove, edit, or lock any account or message at any time should it be seen fit. You also agree that any information you enter on this discussion system is stored in a database, and that "cookies" are stored on your computer to save your login information.';
$l['agreement_4'] = 'Any information you provide on these forums will not be disclosed to any third party without your complete consent, although the staff cannot be held liable for any hacking attempt in which your data is compromised.';
$l['agreement_5'] = 'Nastavljajući sa postupkom registracije slažete se s gore navedenim pravilima kao i bilo kojim dodatnim pravilima koja odredi administrator.';
$l['registration'] = 'Registracija';
$l['required_fields'] = 'Obvezna polja';
$l['complex_password'] = '<acronym title="Lozinka koja je bar {1} znakova duga i sadrži veliko slovo, malo slovo i broj.">Složena</acronym> Lozinka:';
$l['confirm_email'] = 'Potvrdi e-mail:';
$l['optional_fields'] = 'Neobavezna polja';
$l['website_url'] = 'URL vaše stranice:';
$l['birthdate'] = 'Rođendan:';
$l['additional_info'] = 'Dodatni podaci';
$l['required_info'] = 'Potrebni podaci';
$l['i_agree'] = 'Slažem se';
$l['account_details'] = 'Pojedinosti računa';
$l['account_prefs'] = 'Postavke računa:';
$l['invisible_mode'] = 'Sakrij me sa popisa korisnika aktivnih na forumu.';
$l['allow_notices'] = 'Primanje e-maila od administratora.';
$l['hide_email'] = 'Sakriti e-mail od ostalih članova.';
$l['email_notify'] = 'Automatsko praćenje tema u kojima pišete.';
$l['receive_pms'] = 'Primanje privatnih poruka od drugih korisnika.';
$l['pm_notice'] = 'Obavijesti me bilješkom o novoj privatnoj poruci.';
$l['email_notify_newpm'] = 'Obavijesti me e-mailom kada primim novu privatnu poruku.';
$l['time_offset'] = 'Vremenska zona (<acronym title="Daylight Saving Time">DST</acronym> ljetno računanje vremena isključeno):';
$l['time_offset_desc'] = 'Ako živite u vremenskoj zoni koja se razlikuje od ove koja je postavljena na forumu, možete je odabrati na popisu ispod.';
$l['dst_correction'] = 'Ljetno računanje vremena:';
$l['dst_correction_auto'] = 'Automatski nađi DST ljetne postavke';
$l['dst_correction_enabled'] = 'Uvijek koristi DST ljetne računanje';
$l['dst_correction_disabled'] = 'Nikad ne koristi DST ljetnje računanje';
$l['redirect_registered_coppa_activate'] = 'Hvala vam što ste se registrirali na forumu {1}, {2}. Vaš račun je uspješno napravljen, međutim, kako je vlasnik ovog računa mlađi od 13, potrebno je vidjeti dozvolu roditelja prije nego što ovaj račun može biti korišten.<br /><br />Roditelj ili zakoniti skrbnik treba preuzeti, ispuniti i podnijeti nam upotpunjenu kopiju našeg <a href="member.php?action=coppa_form">COPPA slaganja i obrasca dozvole</a>.<br /><br />Kada dobijemo upotpunjenu kopiju ovog obrasca, račun će biti aktiviran.';
$l['coppa_compliance'] = 'COPPA slaganje';
$l['coppa_desc'] = 'Da biste se registrirali na ovaj forum, trebate potvrditi svoju dob da bi bilo u skladu s <a href="http://coppa.org/" title="Children\'s Online Privacy Protection Act" target="_blank">COPPA</a>. Molimo ispod unesite datum rođenja.<br /><br />Ako imate manje od 13 godina, trebate dopuštenje roditelja prije registracije. Roditelj ili skrbnik treba preuzeti, ispuniti te poslati ispunjenu kopiju naše <a href="member.php?action=coppa_form" target="_blank">COPPA forme</a>.';
$l['hide_dob'] = 'Možete odabrati skrivanje vašega datuma rođenja i starosti uređivanjem vašeka korisničkog profila nakon registracije.';
$l['signature'] = 'Potpis:';
$l['continue_registration'] = 'Nastavi s registracijom';
$l['birthdayprivacy'] = 'Privatnost datuma rođenja:';
$l['birthdayprivacyall'] = 'Prikaži godine i datum rođenja';
$l['birthdayprivacynone'] = 'Sakrij godine i datum rođenja';
$l['birthdayprivacyage'] = 'Prikaži samo godine';
$l['leave_this_field_empty'] = 'Ostavi ovo polje prazno:';
$l['error_need_to_be_thirteen'] = 'Trebate imati 13 ili više godina za registraciju na ovaj forum.';
$l['coppa_registration'] = 'COPPA registracjski obrazac';
$l['coppa_form_instructions'] = 'Molimo ispišitze ovaj obrazac, ispunite ga i pošaljite ga bilo faksom na broj ispod bilo e-mailom na ponuđenu e-mail adresu.';
$l['fax_number'] = 'Broj faksa:';
$l['mailing_address'] = 'E-mail adresa:';
$l['account_information'] = 'Podaci računa';
$l['parent_details'] = 'Podaci roditelja / skrbnika';
$l['full_name'] = 'Puno ime:';
$l['relation'] = 'Srodstvo:';
$l['phone_no'] = 'Telefon:';
$l['coppa_parent_agreement'] = 'Razumijem da su podaci koje sam dao istiniti, te da bilo koji podatak može da biti promijenjen u budućnosti unosom dostavljene lozinke kao i da ovaj korisnički račun može biti uklonjen po zahtijevu.';
$l['coppa_agreement_1'] = 'Korisnici mlađi od 13 godina moraju dobiti dozvolu roditelja ili zakonitog skrbnika da bi se registrirali na forum {1}.';
$l['coppa_agreement_2'] = 'Roditelj ili zakoniti skrbnik treba preuzeti, ispuni i podnesti nam upotpunjenu kopiju našeg <a href="member.php?action=coppa_form" target="_blank">COPPA slaganje i obrasca dozvole</a> prije nego što vam članstvo bude osigurano.';
$l['coppa_agreement_3'] = 'Ukoliko to želite, možete započeti postupak registracije sada, ali će nalog biti nepristupačan sve dok gornji obrazac suglasnosti ne bude zaprimljen.';
$l['error_invalid_birthday'] = 'Niste ispravno unijeli rođendan. Molimo unesite rođendan ispravno.';
$l['error_awaitingcoppa'] = 'Ne možete se prijaviti koristeći ovaj račun pošto još uvijek čekamo COPPA potvrdu od roditelja ili skrbnika.<br /><br />Roditelj ili zakoniti skrbnik treba preuzeti, ispuniti i podnijeti nam upotpunjenu kopiju našeg <a href="member.php?action=coppa_form">COPPA slaganja i obrasca dozvole</a>.<br /><br />Kada dobijemo upotpunjenu kopiju ovog obrasca, račun će biti aktiviran.';
$l['lang_select'] = 'Postavke jezika:';
$l['lang_select_desc'] = 'Ukoliko se govorni jezik zemlje u kojoj živite razlikuje od osnovnog jezika ovomga foruma, možda ga možete izabrati ispod, ukoliko je dostupan.';
$l['lang_select_default'] = 'Koristi osnovno';
$l['submit_registration'] = 'Registriraj me!';
$l['confirm_password'] = 'Potvrdi lozinku:';
$l['referrer'] = 'Preporuka:';
$l['referrer_desc'] = 'Ako vam je neki član preporučio ovaj forum, možete unijeti njegovo korisničko ime ispod. Ako niste, jednostavno ostavite ovo polje prazno.';
$l['search_user'] = 'Traži korisnika';
$l['resend_activation'] = 'Ponovno slanje aktivacije računa';
$l['request_activation'] = 'Zatraži aktivacijski kod';
$l['ppp'] = 'Poruka po stranici:';
$l['ppp_desc'] = 'Možete izabrati broj poruka koje će biti prikazane po stranici u temi.';
$l['tpp'] = 'Tema po stranici:';
$l['tpp_desc'] = 'Možete izabrati broj tema koje će biti prikazane po stranici određenog foruma.';
$l['reset_password'] = 'Resetiraj lozinku';
$l['send_password'] = 'Pošalji novu lozinku!';
$l['registration_errors'] = 'Slijedeće greške su se pojavile tokom vaše registracije:';
$l['timeonline'] = 'Vrijeme provedeno na forumu:';
$l['timeonline_hidden'] = '(Hidden)';
$l['registrations_disabled'] = 'Žao nam je, ali u ovom se trenutku ne možete registrirati jer je administrator onemogućio otvaranje novih računa.';
$l['error_username_length'] = 'Vaše korisničko ime nije ispravno. Korisničko ime mora biti između {1} i {2} znakova.';
$l['error_stop_forum_spam_spammer'] = 'Žao nam je, vaše {1} se poklapa sa nekim od poznatog spamera. Ako mislite da je ovo pogreška, molimo vas, kontaktirajte administratora.';
$l['error_stop_forum_spam_fetching'] = 'Žao nam je, nešto je krenulo krivo tokom provjere vašeg računa u bazi spamera. Najverojatnije se bazi ne može pristupiti. Molimo pokušajte ponovno kasnije.';
$l['none_registered'] = 'Neutvrđeno';
$l['not_specified'] = 'Nije određeno';
$l['membdayage'] = '({1} godina)';
$l['mod_options'] = 'Moderatorske opcije';
$l['edit_in_mcp'] = 'Uredi ovog korisnika u Moderatorskoj ploči';
$l['ban_in_mcp'] = 'Baniraj ovog korisnika u Moderatorskoj ploči';
$l['purgespammer'] = 'Izbaci spamera';
$l['edit_usernotes'] = 'Uredi bilješke korisnika u Moderatorskoj ploči';
$l['no_usernotes'] = 'Trenutno nema bilješki za ovog korisnika';
$l['view_all_notes'] = 'Pregledaj sve bilješke';
$l['view_notes_for'] = 'Pregledaj bilješke za {1}';
$l['reputation'] = 'Ugled:';
$l['reputation_vote'] = 'Ocjeni';
$l['reputation_details'] = 'Pojedinosti';
$l['already_logged_in'] = 'Bilješka: Trenutno ste već prijavljeni kao {1}.';
$l['admin_edit_in_acp'] = 'Uredi ovog korisnika u Administratorskoj ploči';
$l['admin_ban_in_acp'] = 'Baniraj ovog korisnika u Administratorskoj ploči';
$l['admin_options'] = 'Postavke administratora';
$l['redirect_registered_activation'] = 'Zahvaljujemo vam se na registraciji na {1}, {2}.<p>Za dovršenje registracije, provjerite e-mail za uputstva o aktivaciji računa. Dok ne aktivirate vaš račun nećete biti u mogućnosti pisati na ovom forumu';
$l['redirect_emailupdated'] = 'Uspješno ste promijenili vaš e-mail.<br />Sada ćete biti vraćeni na početnu stranicu.';
$l['redirect_accountactivated'] = 'Vaš račun je uspješno aktiviran.<br />Sada ćete biti vraćeni na početnu stranicu.';
$l['redirect_accountactivated_admin'] = 'Vaš e-mail je uspješno potvrđen.<br />Vaša registracija sada mora biti aktivirana od administratora. Do tada, nećete biti u mogućnosti pisati na ovom forumu.<br />Sada ćete biti vraćeni na početnu stranicu.';
$l['redirect_registered'] = 'Zahvaljujemo vam se na registraciji na {1}, {2}.<br />Sada ćete biti vraćeni na glavnu stranicu.';
$l['redirect_registered_admin_activate'] = 'Zahvaljujemo vam se na registraciji na {1}, {2}.<br />Vaša registracija mora biti aktivirana od administratora. Do tada, nećete imati mogućnost pisanja na ovom forumu.';
$l['redirect_loggedout'] = 'Uspješno ste se odjavili.<br />Sada ćete biti vraćeni na početnu stranicu.';
$l['redirect_alreadyloggedout'] = 'Već ste se odjavili ili se još niste prijavili.<br />Sada ćete biti vraćeni na početnu stranicu foruma.';
$l['redirect_lostpwsent'] = 'Hvala vam, svi podaci računa vezani uz ovu e-mail adresu poslani su vam na e-mail sa pojedinostima kako da resetirate lozinku.<br /><br />Sada ćete biti vraćeni na početnu stranicu foruma.';
$l['redirect_activationresent'] = 'Vaš aktivacijski e-mail je ponovo poslan.';
$l['redirect_passwordreset'] = 'Hvala vam, lozinka za vaš račun je resetirana. Nova slučajno izvedena lozinka poslana je na e-mail adresu vašeg korisničkog računa.';
$l['redirect_memberrated'] = 'Član je uspješno ocjenjen.';
$l['redirect_registered_passwordsent'] = 'Nova lozinka je izvedena i poslana na vaš e-mail. Prije nego se možete prijaviti na ovaj forum, trebate provijeriti vaš e-mail za ovu lozinku.';
$l['redirect_validated'] = 'Hvala vam, vaš račun je potvrđen.<br />Sada ćete biti vraćeni na forum.';
$l['error_activated_by_admin'] = 'Ne možete ponovo poslati aktivacijski e-mail za vaš račun jer sve registracije moraju biti odobrene od administratora.';
$l['error_alreadyregistered'] = 'Žao nam je, ali naš sistem pokazuje da ste se već registrirali na ovom forumu a otvaranje više korisničkih računa nije dopušteno.';
$l['error_alreadyregisteredtime'] = 'Ne možemo prihvatiti vaš zahtijev za registraciju jer već postoji {1} novi zahtijev za registracijom(ama) sa vaše ip adrese u posljednjih {2} sat(i). Molimo pokušajte ponovno kasnije.';
$l['error_badlostpwcode'] = 'Izgleda da ste unijeli neispravan kod za resetiranje lozinke. Molimo ponovo-pročitajte e-mail koji vam je poslan ili kontaktirajte administratora foruma za pomoć.';
$l['error_badactivationcode'] = 'Unijeli ste neispravan kod za aktivaciju računa. Za ponovno slanje svih aktivacijskih e-maliova, kliknite <a href="member.php?action=resendactivation">ovdje</a>.';
$l['error_alreadyactivated'] = 'Vaš račun je već aktiviran ili ne zahtijeva e-mail potvrdu.';
$l['error_alreadyvalidated'] = 'Vaš e-mail je već potvrđen.';
$l['error_nothreadurl'] = 'Vaša poruka ne sadrži URL teme. Molimo koristite mogućnost "pošalji temu prijatelju" za ovu svrhu.';
$l['error_bannedusername'] = 'Unijeli ste korisničko ime koje je zabranjeno za registriranje.  Molimo izaberite drugo korisničko ime.';
$l['error_notloggedout'] = 'Vaš korisnički ID ne može biti potvrđen kako bi vas odjavio.  Ovo je možda zbog toga što vas je neka greška u JavaScriptu pokušala odjaviti automatski. Ako se želite odjaviti, molimo kliknite na link odjava pri vrhu.';
$l['error_regimageinvalid'] = 'Unijeti kod sa slike za potvrdu nije ispravan. Molimo upišite kod točno onako kakav je prikazan na slici.';
$l['error_regimagerequired'] = 'Molimo unesite kod sa slike za potvrdu kako biste nastavili sa postupkom prijave. Molimo upišite kod točno onako kako je prikazan na slici.';
$l['error_spam_deny'] = 'Naši sistemi zaključuju da ste vi vjerojatno spamer i zbog toga vam je odbijena registracija. Ako mislite da je ovo greška, molimo kontaktirajte administratora.';
$l['error_spam_deny_time'] = 'Naš sistem je zaključio da ste vi mogući spamer pa vam je odbijena registracija.  Registiranje mora trajati najmanje {1} sekundi za spriječavanje automatskih registracija, a vi ste se registrirali za samo {2} sekundi. Ako mislite da je ovo greška, molimo kontaktirajte administratora.';
$l['js_validator_no_username'] = 'Morate unijeti korisničko ime';
$l['js_validator_invalid_email'] = 'Trebate unijeti ispravnu e-mail adresu';
$l['js_validator_email_match'] = 'Trebate ponovno unijeti istu e-mail adresu';
$l['js_validator_no_image_text'] = 'Trebate unijeti tekst sa slike iznad';
$l['js_validator_no_security_question'] = 'Potrebno je unijeti odgovor na pitanje iznad';
$l['js_validator_password_matches'] = 'Lozinke koje ste unijeli moraju biti jednake';
$l['js_validator_password_complexity'] = 'Proveravanje složenosti lozinke';
$l['js_validator_password_length'] = 'Vaša lozinka mora biti duga {1} ili više znakova';
$l['js_validator_not_empty'] = 'Morate izabrati ili unijeti vrijednost za ovo polje';
$l['js_validator_checking_username'] = 'Provjera je li korisničko ime dostupno';
$l['js_validator_username_length'] = 'Korisnička imena moraju biti duga između {1} i {2} znakova';
$l['js_validator_checking_referrer'] = 'Provjera da li korisničko ime preporučitelja postoji.';
$l['js_validator_captcha_valid'] = 'Provjera jeste li ste ili niste unijeli ispravan kod za potvrdu sa slike.';
$l['security_question'] = 'Sigurnosno pitanje';
$l['question_note'] = 'Molimo odgovorite na postavljeno pitanje. Ovaj postupak se koristi za spriječavanje automatskih ispuna.';
$l['error_question_wrong'] = 'Odgovor koji ste pružili za sigurnosno pitanje je pogrešan. Molimo pokušajte ponovno.';
$l['subscription_method'] = 'Osnovni način praćenja tema:';
$l['no_auto_subscribe'] = 'Ne prati teme';
$l['no_subscribe'] = 'Bez obavijesti';
$l['instant_email_subscribe'] = 'Trenutna e-mail obavijest';
$l['instant_pm_subscribe'] = 'Trenutna obavijest privatnom porukom';
$l['remove_from_buddy_list'] = 'Ukloni sa popisa prijatelja';
$l['add_to_buddy_list'] = 'Dodaj na popis prijatelja';
$l['remove_from_ignore_list'] = 'Ukloni sa popis za ignoriranje';
$l['add_to_ignore_list'] = 'Dodaj na popis za ignoriranje';
$l['report_user'] = 'Prijavi korisnika';
$l['newregistration_subject'] = 'Nova registracija na {1}';
$l['newregistration_message'] = '{1},

Postoji novi korisnik na {2} koji čeka administratorsku aktivaciju računa.

Korisničko ime: {3}

Hvala vam,
{2} Uprava';
$l['ban_remaining'] = 'ostaje';
$l['registration_ip'] = 'Registracijska IP adresa';
$l['last_known_ip'] = 'Zadnja poznata IP adresa:';
$l['js_validator_bad_password_security'] = 'Lozinka koju ste unijeli je slična ili vašem korisničkom imenu ili e-mail adresi. Molimo vas da unesete kompleksniju lozinku.';
$l['nav_referrals'] = 'Korisnici koje je preporučio {1}';
$l['referrals'] = 'Preporuke';
$l['referral_date'] = 'Datum Preporuke:';
$l['referrals_no_user_specified'] = 'Korisnik nije naveden.';
$l['member_no_referrals'] = 'Nema preporuka za ovoga korisnika.';
$l['coppa_desc_for_deny'] = 'Da biste se registrirali na ovaj forum, trebate potvrditi svoju dob da bi bilo u skladu s <a href="http://coppa.org/" title="Children\'s Online Privacy Protection Act" target="_blank" rel="noopener">COPPA</a>. Molimo ispod unesite datum rođenja.';
$l['edit_ban_in_mcp'] = 'Uredi Ban u Moderatorskoj ploči';
$l['lift_ban_in_mcp'] = 'Produlji Ban u Moderatorskoj ploči';
