<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1813
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sun, 19 Apr 2020 13:36:32 +0000
// --------------------------------------------------------------------------------

$l['click_no_wait'] = 'Kliknite ovdje ako više ne želite čekati.';
$l['redirect_return_forum'] = '<br /><br />Kliknite ovdje, <a href="{1}">za povratak na forum</a>.';
$l['redirect_emailsent'] = 'Vaša e-mail poruka je uspješno poslana.';
$l['redirect_loggedin'] = 'Uspešno ste prijavljeni.<br />Sada ćete biti vraćeni na stranicu sa koje ste se prijavili.';
$l['error_invalidpworusername'] = 'Unijeli ste neispravnu kombinaciju korisničkog imena/lozinke. <br /><br />Ako ste zaboravili vašu lozinku, molimo <a href="member.php?action=lostpw">zatražite novu</a>.';
$l['error_invalidpworusername1'] = 'Unijeli ste neispravnu kombinaciju e-maila/lozinke. <br /><br />Ako ste zaboravili vašu lozinku, molimo <a href="member.php?action=lostpw">zatražite novu</a>.';
$l['error_invalidpworusername2'] = 'Unijeli ste neispravnu kombinaciju korisničkog imena/lozinke ili e-maila/lozinke. <br /><br />Ako ste zaboravili vašu lozinku, molimo <a href="member.php?action=lostpw">zatražite novu</a>.';
$l['error_incompletefields'] = 'Ostavili ste prazno jedno ili više potrebnih polja. Molimo vas da popunite sva tražena polja.';
$l['error_alreadyuploaded'] = 'Ova poruka već sadrži prilog s imenom "{1}". Molimo preimenujte datoteku pa pokušajte ponovno. Ili možete kliknuti na "Ažuriraj prilog"';
$l['error_alreadyuploaded_perm'] = 'Ova poruka već sadrži prilog s istim imenom. Molimo maknite prvu datoteku ili preimenujte novu datoteku pa pokušajte ponovno.';
$l['error_nomessage'] = 'Žao nam je ali ne možemo nastaviti jer niste unijeli ispravnu poruku. Molimo vas da se vratite natrag i pokušate ponovno.';
$l['error_invalidemail'] = 'Niste unijeli ispravnu e-mail adresu.';
$l['error_nomember'] = 'Upisano ime člana nije ispravno ili član ne postoji.';
$l['error_maxposts'] = 'Žao nam je, ali dostigli ste ograničenje poruka koje možete napisati u jednom danu.  Molimo sačekajte do sutra za novu poruku ili kontaktirajte administratora foruma za pomoć.<br /><br />Najveći broj poruka koji možete poslati u jednom danu je {1}';
$l['error_nohostname'] = 'Nije moguće naći server za IP adresu koju ste upisali.';
$l['error_invalidthread'] = 'Navedena tema ne postoji.';
$l['error_invalidpost'] = 'Navedena poruka ne postoji.';
$l['error_invalidannouncement'] = 'Navedena najava ne postoji.';
$l['error_invalidattachment'] = 'Navedeni prilog ne postoji.';
$l['error_invalidforum'] = 'Neispravan forum';
$l['error_closedinvalidforum'] = 'Ne možete pisati u ovom forumu jer je zaključan, forum preusmjerenja na drugu web stranicu, ili je kategorija.';
$l['error_attachtype'] = 'Tip datoteke koju ste priložili nije dozvoljen. Molimo vas da uklonite prilog ili izaberite drugi tip.';
$l['error_attachsize'] = 'Prilog "{1}" je prevelik. Najveća dozvoljena veličina za taj tip priloga je {2} kilobytes.';
$l['error_uploadempty'] = 'Datoteka "{1}" je prazna.';
$l['error_uploadsize'] = 'Veličina izabrane datoteke je prevelika.';
$l['error_uploadfailed'] = 'Podizanje datoteke na forum nije uspjelo. Molimo izaberite ispravnu datoteku i probajte ponovo. ';
$l['error_uploadfailed_detail'] = 'Pojedinosti greške: ';
$l['error_uploadfailed_php1'] = 'PHP prijavljuje: podignuta datoteka premašuje upload_max_filesize odredbe u php.ini.  Molimo vas da kontaktirate administratora foruma za ovu grešku.';
$l['error_uploadfailed_php2'] = 'Datoteka za upload premašuju najveću dozvoljenu veličinu.';
$l['error_uploadfailed_php3'] = 'Datoteka za upload je samo dijelomično prenesena.';
$l['error_uploadfailed_php4'] = 'Niti jedna datoteka nije uploadana.';
$l['error_uploadfailed_php6'] = 'PHP vraća: Nedostaje privremena mapa. Molimo vas da kontaktirate administratora o ovome problemu.';
$l['error_uploadfailed_php7'] = 'PHP vraća: Nije moguće se pisati po disku. Molimo vas da kontaktirate administratora o ovome problemu.';
$l['error_uploadfailed_phpx'] = 'PHP vraća kod greške: {1}.  Molimo vas da kontaktirate administratora o ovome problemu.';
$l['error_uploadfailed_nothingtomove'] = 'Neispravna datoteka je navedena, pa datoteka za upload ne može biti premještena na njenu destinaciju.';
$l['error_uploadfailed_movefailed'] = 'Pojavio se problem kod premještanja uploadane datoteke na njenu destinaciju.';
$l['error_uploadfailed_lost'] = 'Prilog nije pronađen na serveru.';
$l['error_emailmismatch'] = 'E-mail adrese koje ste unijeli se ne poklapaju. Polimo vas da se vratite i pokušate ponovno.';
$l['error_nopassword'] = 'Niste unijeli ispravnu lozinku.';
$l['error_usernametaken'] = 'Korisničko ime koje ste unijeli je već registrirano. Ako ste se prethodno registrirali an forum, molimo vas da se <a href="member.php?action=login">prijavite</a>.';
$l['error_nousername'] = 'Niste unijeli korisničko ime.';
$l['error_invalidusername'] = 'Korisničko ime koje ste unijeli nije ispravno.';
$l['error_invalidpassword'] = 'Niste unijeli ispravnu lozinku. Ako ste zaboravili vašu lozinku, kliknite <a href="member.php?action=lostpw">ovdje</a>. Ili se vratite natrag i pokušajto ponovno.';
$l['error_postflooding'] = 'Žao nam je ali nije moguće poslati vašu poruku. Administrator je naveo da vam je dozvoljeno pisati jednu poruku svcakih {1} sekundi.';
$l['error_nopermission_guest_1'] = 'Vi ili niste prijavljeni ili nemate dopuštenje da biste vidjeli ovu stranicu. Ovo može biti zbog slijedećih razloga:';
$l['error_nopermission_guest_2'] = 'Niste prijavljeni ili registrirani. Molimo koristite formu na dnu stranice za prijavu.';
$l['error_nopermission_guest_3'] = 'Nemate dopuštenje za pristupn ovoj stranici. Pokušavate li pristupiti administrativnim stranicama ili resursima kojima nebiste trebali? Provjerite u pravilima imate li dozvolu za izvršavanje ove akcije.';
$l['error_nopermission_guest_4'] = 'Vaš korisnički račun je odbijen od strane administratora ili još čeka aktivaciju.';
$l['error_nopermission_guest_5'] = 'Vi ste pristupili ovoj stranici direktno a ne prikladnim formama ili linkovima.';
$l['login'] = 'Prijava';
$l['need_reg'] = 'Trebate se registrirati?';
$l['forgot_password'] = 'Zaboravili ste lozinku?';
$l['error_nopermission_user_1'] = 'Nemate dopuštenje za pristup ovoj stranici. Ovo može biti zbog slijedećih razloga:';
$l['error_nopermission_user_ajax'] = 'Nemate dopuštenje za pristup ovoj stranici.';
$l['error_nopermission_user_2'] = 'Vaš račun je suspendiran ili ste banirani od pristupa ovoj stranici.';
$l['error_nopermission_user_3'] = 'Trebate dopuštenje za pristup ovoj stranici. Pokušavate li priostupiti administrativnim stranicama ili stranicama na kojima ne biste smeli biti? Provjerite forumska pravila koko biste povjerili smijete li izvršili ovu akciju.';
$l['error_nopermission_user_4'] = 'Vaš račun vjerojatno još uvjek zahtjeva aktivaciju ili moderaciju.';
$l['error_nopermission_user_5'] = 'Pristupili ste ovoj stranici direktno a ne koristeći potrebne forme ili link.';
$l['error_nopermission_user_resendactivation'] = 'Ponovno pošalji aktivacijski kod';
$l['error_nopermission_user_username'] = 'Trenutno ste prijavljeni s korisničkim imenom: \'{1}\'';
$l['logged_in_user'] = 'Prijavljeni korisnik';
$l['error_too_many_images'] = 'Previše slika.';
$l['error_too_many_images2'] = 'Žao nam je, ne možemo nastaviti do vašeg posta jer sadrži  previše slika. Molimo vas da maknete neke slike iz posta prije nastavka.';
$l['error_too_many_images3'] = '<b>Pažnja:</b> Najveći mogući broj slika po postu je';
$l['error_attach_file'] = 'Greška priloženja datoteke';
$l['please_correct_errors'] = 'Molimo ispravite slijedeće greške prije nastavka:';
$l['error_reachedattachquota'] = 'Žao nam je ali ne možete priložiti datoteku jer ste dosagli najveću kvotu priloga od {1}';
$l['error_maxattachpost'] = 'Žao nam je ali ne možete priložiti ovu datoteku jer ste dosegli maksimum priloga po postu. Najviše dozvoljeno je {1}';
$l['error_invaliduser'] = 'Navedeni korisnik je neispravan ili ne postoji.';
$l['error_invalidaction'] = 'Neispravna akcija';
$l['error_messagelength'] = 'Žao nam je, vaša je poruka preduga i ne može biti poslana. Molimo vas da je skratite i pokušate ponovno.';
$l['error_message_too_short'] = 'Žao nam je, vaša je poruka prekratka i ne može biti poslana.';
$l['failed_login_wait'] = 'Niste se uspijeli prijaviti s dopuštenim brojem pokušaja. Sada trebate sačekati {1} sati {2} minuta {3} sekundi prije nego možete pokušati ponovno.';
$l['failed_login_again'] = '<br />Imate još <strong>{1}</strong> doopuštenih pokušaja prijave.';
$l['error_max_emails_day'] = 'Ne možete koristiti funkciju \'pošalji prijatelju\' ili \'pošalji e-mail korisniku\' jer ste već dosegli dozvoljenu kvotu od slanja {1} poruka u 24 sata.';
$l['attachments_disabled'] = 'Ne možete koristiti sistem priloga jer nije odobren od strane administratora.';
$l['emailsubject_lostpw'] = 'Reset lozinke na {1}';
$l['emailsubject_passwordreset'] = 'Nova lozinka na {1}';
$l['emailsubject_subscription'] = 'Odgovor na {1}';
$l['emailsubject_randompassword'] = 'Vaša lozinka za {1}';
$l['emailsubject_activateaccount'] = 'Aktivacija računa na {1}';
$l['emailsubject_forumsubscription'] = 'Nova tema u {1}';
$l['emailsubject_reportpost'] = 'Prijavljeni post na {1}';
$l['emailsubject_reachedpmquota'] = 'Kvota privatnih poruka dokučena na {1}';
$l['emailsubject_changeemail'] = 'Promjena e-maila na {1}';
$l['emailsubject_newpm'] = 'Nova privatna poruka na {1} - {2}';
$l['emailsubject_newjoinrequest'] = 'Novi zahtjev za pridruživanjem na {1}';
$l['emailsubject_sendtofriend'] = 'Zanimljivi razgovor na {1}';
$l['emailsubject_changepassword'] = 'Promjena lozinke na {1}';
$l['emailbit_viewthread'] = '... (posjeti temu da biste pročitali više...)';
$l['email_lostpw'] = '{1},

Da biste resetirali lozinku vašega računa na {2}, trebati ćete ići na URL ispod vašim pretraživačem.

{3}/member.php?action=resetpassword&uid={4}&code={5}

Ako vam gornji link ne radi, posjetite ovu adresu:

{3}/member.php?action=resetpassword

Trebati ćete unijeti slijedeće:
Korisničko ime: {1}
Aktivacijski kod: {5}

Zahvaljujemo,
{2} osoblje';
$l['email_lostpw1'] = '{1},

Da biste resetirali lozinku vašega računa na {2}, trebati ćete ići na URL ispod vašim pretraživačem.

{3}/member.php?action=resetpassword&uid={4}&code={5}

Ako vam gornji link ne radi, posjetite ovu adresu:

{3}/member.php?action=resetpassword

Trebati ćete unijeti slijedeće:
Vaš e-mail
Aktivacijski kod: {5}

Zahvaljujemo,
{2} osoblje';
$l['email_lostpw2'] = '{1},

Da biste resetirali lozinku vašega računa na {2}, trebati ćete ići na URL ispod vašim pretraživačem.

{3}/member.php?action=resetpassword&uid={4}&code={5}

Ako vam gornji link ne radi, posjetite ovu adresu:

{3}/member.php?action=resetpassword

Trebati ćete unijeti slijedeće:
Korisničko ime: {1} (ili vaš e-mkail)
Aktivacijski kod: {5}

Zahvaljujemo,
{2} osoblje';
$l['email_reportpost'] = '{1} od {2} je prijavio slijedeći post:

{3}
{4}/{5}

Razlog koji je korisnik naveo za prijavu posta:
{7}

Ova poruka je poslana svim moderatorima ovoga foruma, ili supermoderatorima i administratorima ako taj forum nema moderatora.

Molimo vas da provjerite taj post što je prije moguće.';
$l['email_passwordreset'] = '{1},

Vaša lozinka na {2} je resetirana.

Vaša nova lozinka je: {3}

Trebati ćete ovuYou will need this password to login to the forums, once you login you should change it by going to your User Control Panel.

Thank you,
{2} Staff';
$l['email_randompassword'] = '{1},

Thank you for registering on {2}. Below is your username and the randomly generated password. To login to {2}, you will need these details.

Username: {3}
Password: {4}

It is recommended you change your password immediately after you login. You can do this by going to your User CP then clicking Change Password on the left menu.

Thank you,
{2} Staff';
$l['email_randompassword1'] = '{1},

Thank you for registering on {2}. Below is your username and the randomly generated password. To login to {2}, you will need these details.

Your email address
Password: {4}

It is recommended you change your password immediately after you login. You can do this by going to your User CP then clicking Change Password on the left menu.

Thank you,
{2} Staff';
$l['email_randompassword2'] = '{1},

Thank you for registering on {2}. Below is your username and the randomly generated password. To login to {2}, you will need these details.

Username: {3} (Or your email address)
Password: {4}

It is recommended you change your password immediately after you login. You can do this by going to your User CP then clicking Change Password on the left menu.

Thank you,
{2} Staff';
$l['email_sendtofriend'] = 'Hello,

{1} from {2} thought you may be interested in reading the following web page:

{3}

{1} included the following message:
------------------------------------------
{4}
------------------------------------------

Thank you,
{2} Staff
';
$l['email_forumsubscription'] = '{1},

{2} has just started a new thread in {3}. This is a forum you have subscribed to at {4}.

The thread is titled {5}

Here is an excerpt of the message:
--
{6}
--

To view the thread, you can go to the following URL:
{7}/{8}

There may also be other new threads and replies but you will not receive anymore notifications until you visit the board again.

Thank you,
{4} Staff

------------------------------------------
Unsubscription Information:

If you would not like to receive any more notifications of new threads in this forum, visit the following URL in your browser:
{7}/usercp2.php?action=removesubscription&type=forum&fid={9}&my_post_key={10}

------------------------------------------';
$l['email_activateaccount'] = '{1},

To complete the registration process on {2}, you will need to go to the URL below in your web browser.

{3}/member.php?action=activate&uid={4}&code={5}

If the above link does not work correctly, go to

{3}/member.php?action=activate

You will need to enter the following:
Username: {1}
Activation Code: {5}

Thank you,
{2} Staff';
$l['email_activateaccount1'] = '{1},

To complete the registration process on {2}, you will need to go to the URL below in your web browser.

{3}/member.php?action=activate&uid={4}&code={5}

If the above link does not work correctly, go to

{3}/member.php?action=activate

You will need to enter the following:
Your email address
Activation Code: {5}

Thank you,
{2} Staff';
$l['email_activateaccount2'] = '{1},

To complete the registration process on {2}, you will need to go to the URL below in your web browser.

{3}/member.php?action=activate&uid={4}&code={5}

If the above link does not work correctly, go to

{3}/member.php?action=activate

You will need to enter the following:
Username: {1} (Or your email address)
Activation Code: {5}

Thank you,
{2} Staff';
$l['email_subscription'] = '{1},

{2} has just replied to a thread which you have subscribed to at {3}. This thread is titled {4}.

Here is an excerpt of the message:
------------------------------------------
{5}
------------------------------------------

To view the thread, you can go to the following URL:
{6}/{7}

There may also be other replies to this thread but you will not receive anymore notifications until you visit the board again.

Thank you,
{3} Staff

------------------------------------------
Unsubscription Information:

If you would not like to receive any more notifications of replies to this thread, visit the following URL in your browser:
{6}/usercp2.php?action=removesubscription&tid={8}&my_post_key={9}

------------------------------------------';
$l['email_reachedpmquota'] = '{1},

This is an automated email from {2} to let you know that your Private Messaging inbox has reached its capacity.

One or more users may have tried to send you private messages and were unsuccessful in doing so because of this.

Please delete some of your private messages you currently have stored, remembering to also delete them from the \'Trash Can\'.

Thank you,
{2} Staff
{3}';
$l['email_changeemail'] = '{1},

We have received a request on {2} to change your email address (see details below).

Old Email Address: {3}
New Email Address: {4}

If these changes are correct, please complete the validation process on {2} by going to the following URL in your web browser.

{5}/member.php?action=activate&uid={8}&code={6}

If the above link does not work correctly, go to

{5}/member.php?action=activate

You will need to enter the following:
Username: {7}
Activation Code: {6}

If you choose not to validate your new email address your profile will not be updated and will still contain your existing email address.

Thank you,
{2} Staff
{5}';
$l['email_changeemail_noactivation'] = '{1},

We have received a request on {2} to change your email address (see details below).

Old Email Address: {3}
New Email Address: {4}

This change has been automatically processed. If you did not request this change, please get it touch with an Administrator.

Thank you,
{2} Staff
{5}';
$l['email_changepassword'] = '{1},

You are receiving this email because you, or someone with access to your password, recently changed your account password.

Username: {1}
Email address: {2}

If you did not request this change, please get in touch with an Administrator.

Thank you,
{3} Staff
{4}';
$l['email_newpm'] = '{1},

You have received a new private message on {3} from {2}:

------------------------------------------
{5}
------------------------------------------

To view, reply or forward this message, you can follow this link:

{4}/private.php

Please note that you will not receive any further notifications of new messages until you visit {3}.

You can disable new message notifications on your account options page:

{4}/usercp.php?action=options

Thank you,
{3} Staff
{4}';
$l['email_emailuser'] = '{1},

{2} from {3} has sent you the following message:
------------------------------------------
{5}
------------------------------------------

Thank you,
{3} Staff
{4}

------------------------------------------
Don\'t want to receive email messages from other members?

If you don\'t want other members to be able to email you please visit your User Control Panel and enable the option \'Hide your email from other members\':
{4}/usercp.php?action=options

------------------------------------------';
$l['email_groupleader_joinrequest'] = '{1},

{2} has requested to join {3} on {4} (see below).

Reason: {5}

To accept or decline this request, go to

{6}/managegroup.php?gid={7}

Thank you,
{4} Staff';
$l['email_contact_subject'] = 'Kontakt: {1}';
$l['email_contact'] = 'E-mail: {1}
Forum profile: {2}
IP Address: {3}
Message:
{4}';
$l['pmsubject_subscription'] = 'New Reply to {1}';
$l['pm_subscription'] = '{1},

{2} has just replied to a thread which you have subscribed to. This thread is titled {3}.

Here is an excerpt of the message:
------------------------------------------
{4}
------------------------------------------

To view the thread, you can go to the following URL:
[url]{5}/{6}[/url]

There may also be other replies to this thread but you will not receive anymore notifications until you visit the thread again.

------------------------------------------
Unsubscription Information:

If you would not like to receive any more notifications of replies to this thread, visit the following URL in your browser:
[url]{5}/usercp2.php?action=removesubscription&tid={7}&my_post_key={8}[/url]

------------------------------------------';
$l['emailsubject_reportprofile'] = 'Prijavljeni korisnik na {1}';
$l['emailsubject_reportreputation'] = 'Prijavljeni ugled na {1}';
$l['email_reportprofile'] = '{1} od {2} je prijavio slijedećeg korisnika:

{3}
{4}/{5}

Razlog koji je korisnik naveo za prijavu korisnika:
{7}

Ova poruka je poslana svim moderatorima ovoga foruma, ili supermoderatorima i administratorima ako taj forum nema moderatora.

Molimo vas da provjerite ovoga korisnika što je prije moguće.';
$l['email_reportreputation'] = '{1} od {2} je prijavio slijedeći ugled:

{3}
{4}/{5}

Razlog koji je korisnik naveo za prijavu ugleda:
{7}

Ova poruka je poslana svim moderatorima ovoga foruma, ili supermoderatorima i administratorima ako taj forum nema moderatora.

Molimo vas da provjerite taj ugled što je prije moguće.';
$l['email_report_comment_extra'] = '{1}: {2}';
$l['email_broken_task_subject'] = 'MyBB greška zadatka na {1}';
$l['email_broken_task'] = 'Vaša kopija MyBB-a na {1} ({2}) je naišla na problem sa sistemom za zadatke.

Datoteka zadatka za {3} nedostaje.

Ovaj zadatak je obustavljen dok se greška ne riješi.';
$l['error_attach_filename_length'] = 'Ime datoteke "{1}" prelazi najveću dopuštenu duljinu imena za datoteke koja je {2}. Molimo vas da podignete datoteku s kraćim imenom.';
