<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1813
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sun, 19 Apr 2020 13:37:05 +0000
// --------------------------------------------------------------------------------

$l['nav_helpdocs'] = 'Dokumenti Pomoći';
$l['nav_smilies'] = 'Popis emotikona';
$l['nav_syndication'] = 'Najnovije teme Syndication (RSS)';
$l['aol_im'] = 'AOL IM';
$l['skype'] = 'Skype';
$l['yahoo_im'] = 'Yahoo IM';
$l['skype_center'] = 'Skype Centar';
$l['skype_status'] = 'Skype Status';
$l['chat_on_skype'] = 'Chat s {1} na Skype';
$l['call_on_skype'] = 'Pozovi {1} preko Skype';
$l['yahoo_center'] = 'Yahoo! Centar';
$l['send_y_message'] = 'Pošalji {1} a Yahoo! poruku.';
$l['view_y_profile'] = 'Pregled {1} Yahoo! Profila.';
$l['aim_center'] = 'AOL IM Centar';
$l['download_aim'] = 'Preuzmi AIM';
$l['aim_remote'] = 'AIM Remote';
$l['send_me_instant'] = 'Pošalji mi Trenutnu Poruku';
$l['add_me_buddy_list'] = 'Dodaj me na svoj popis prijatelja';
$l['add_remote_to_page'] = 'Dodaj Remote na vašu stranicu';
$l['download_aol_im'] = 'Preuzmi AOL Instant messenger';
$l['buddy_list'] = 'Popis';
$l['online'] = 'Online';
$l['online_none'] = '<em>Nemate prijatelja online</em>';
$l['offline'] = 'Offline';
$l['offline_none'] = '<em>Nemate prijatelja offline</em>';
$l['delete_buddy'] = 'X';
$l['pm_buddy'] = 'Pošalji privatnu poruku';
$l['last_active'] = '<strong>Posljednji put aktivan:</strong> {1}';
$l['close'] = 'Zatvori';
$l['no_buddies'] = '<em>Vaša lista prijatelja je trenutno prazna. Koristite vašu kontrolnu ploču ili posjetite profil korisnika da biste dodali korisnike na vaš popis prijatelja.</em>';
$l['help_docs'] = 'Dokumenti pomoći';
$l['search_help_documents'] = 'Pretraži dokumente pomoći';
$l['search_by_name'] = 'Traži po imenu';
$l['search_by_document'] = 'Traži po dokumentu';
$l['enter_keywords'] = 'Unesi keywords';
$l['search'] = 'Traži';
$l['redirect_searchresults'] = 'Hvala vam, vaša potraga je prihvaćena i sada ćete biti odvedeni na popis rezultata.';
$l['search_results'] = 'Rezultati traženja';
$l['help_doc_results'] = 'Rezultati dokumenata pomoći';
$l['document'] = 'Dokument';
$l['error_nosearchresults'] = 'Žao nam je ali nema rezultata koji su pronađeni po vašim kriterijima traženja. Molimo promijenite ih i pokušajte ponovno.';
$l['no_help_results'] = 'Žao nam je ali nema rezultata koji su pronađeni po vašim kriterijima traženja.';
$l['error_helpsearchdisabled'] = 'Opciju za traženje dokumenata pomoći je administrator deaktivirao.';
$l['smilies_listing'] = 'Popis emotikona';
$l['name'] = 'Ime';
$l['abbreviation'] = 'Abbreviation';
$l['click_to_add'] = 'Kliknite na emotikon da biste ga dodali';
$l['close_window'] = 'zatvori prozor';
$l['who_posted'] = 'Tko je pisao?';
$l['total_posts'] = 'Ukupno poruka:';
$l['user'] = 'Korisnik';
$l['num_posts'] = '# poruka';
$l['forum_rules'] = '{1} - Pravila';
$l['error_invalid_limit'] = 'The feed item limit you entered is invalid. Please specify a valid limit.';
$l['syndication'] = 'Posljedenje teme Syndication';
$l['syndication_generated_url'] = 'Your Generated Syndication URL:';
$l['syndication_note'] = 'Below you can generate links to specific RSS syndication feeds. Links can be generated for all forums, per forum, or for a specific number of forums. You will then be presented with a link which you can copy in to an RSS reader. <i><a href="http://en.wikipedia.org/wiki/RSS" target="_blank">What is RSS?</a></i>';
$l['syndication_forum'] = 'Forum za Syndicate:';
$l['syndication_forum_desc'] = 'Molimo izaberite forum desno. Koristite ctrl i klik da biste ih izabrali više.';
$l['syndication_version'] = 'Feed Verzija:';
$l['syndication_version_desc'] = 'Please select the version of the feeds you wish to generate.';
$l['syndication_version_atom1'] = 'Atom 1.0';
$l['syndication_version_rss2'] = 'RSS 2.00 (osnovno)';
$l['syndication_generate'] = 'Generate Syndication URL';
$l['syndication_limit'] = 'Limit:';
$l['syndication_limit_desc'] = 'Količina tema koje mogu biti preuzete odjednom. Ne preporuča se više od 50.';
$l['syndication_threads_time'] = 'tema u vrijeme';
$l['syndicate_all_forums'] = 'Syndicate sve forume';
$l['redirect_markforumread'] = 'Izabrani forum je označen kao pročitan.';
$l['redirect_markforumsread'] = 'Svi forumi su označeni kao pročitani.';
$l['redirect_forumpasscleared'] = 'Spremljena lozinka za ovaj forum je zaboravljena.';
$l['redirect_cookiescleared'] = 'Svi kolačići su očišćeni.';
$l['error_invalidimtype'] = 'Ovaj član nema ovaj tip instant messenger računa naveden u profilu.';
$l['error_invalidhelpdoc'] = 'Čini se da navedeni dokument pomoći ne postoji.';
$l['dst_settings_updated'] = 'Vaše DST postavke su automatski promijenjene.<br /><br />Sada ćete biti vraćeni na forum.';
$l['no_smilies'] = 'Trenutno nema dostupnih smajlića';
$l['error_invalidforum'] = 'Neispravni forum';
$l['error_invalidsearch'] = 'Neispravna pretraga je navedena. Molimo vas da se vratite natrag i pokušate ponovno.';
$l['error_no_search_support'] = 'Databaza ne potržava pretraživanje';
$l['error_searchflooding'] = 'Žao nam je ali možete pretraživati samo jednom svakih {1} sekundi. Molimo sačekajte još {2} sekundi prije nego pokušate opet pretraživati.';
$l['error_searchflooding_1'] = 'Žao nam je ali možete pretraživati samo jednom svakih {1} sekundi. Molimo sačekajte još 1 sekundu prije nego pokušate opet pretraživati.';
$l['syndication_version_json1'] = 'JSON Feed 1';
