<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:12:53 +0000
// --------------------------------------------------------------------------------

$l['nav_portal'] = 'Portal';
$l['posted_by'] = 'Napisano od:';
$l['forum'] = 'Forum:';
$l['replies'] = 'Odgovora';
$l['no_replies'] = 'Bez odgovora';
$l['latest_threads'] = 'Zadnje teme';
$l['latest_threads_replies'] = 'Odgovori:';
$l['latest_threads_views'] = 'Pogledi:';
$l['latest_threads_lastpost'] = 'Zadnja poruka:';
$l['private_messages'] = 'Privatne poruke';
$l['pms_received_new'] = '{1}, imate <b>{2}</b> nepročitanih poruka.';
$l['pms_unread'] = 'Nepročitane poruke';
$l['pms_total'] = 'Ukupno poruka';
$l['search_forums'] = 'Pretraži forume';
$l['advanced_search'] = 'Napredno traženje';
$l['forum_stats'] = 'Statistike foruma';
$l['num_members'] = 'Članovi:';
$l['latest_member'] = 'Najnoviji član:';
$l['num_threads'] = 'Forumske teme:';
$l['num_posts'] = 'Forumski postovi:';
$l['full_stats'] = 'Potpuna statistika';
$l['welcome'] = 'Dobrodošli, {1}';
$l['guest'] = 'gost';
$l['guest_welcome_registration'] = 'Trebate se <a href="{1}">registrirati</a> prije nego možete pisati na ovoj stranici.';
$l['username'] = 'Korisničko ime';
$l['password'] = 'Lozinka';
$l['login'] = 'Prijava!';
$l['member_welcome_lastvisit'] = 'Zadnja posjeta:';
$l['since_then'] = 'Od onda, ovdje je bilo:';
$l['new_announcements'] = '{1} novih obavijesti';
$l['new_announcement'] = '1 nova obavijest';
$l['new_threads'] = '{1} novih tema';
$l['new_thread'] = '1 nova tema';
$l['new_posts'] = '{1} novih poruka';
$l['new_post'] = '1 nova poruka';
$l['view_new'] = 'Pogledaj nove poruke';
$l['view_todays'] = 'Pogledaj današnje poruke';
$l['online'] = 'Korisnici online';
$l['online_user'] = 'Ovdje je trenutno 1 korisnik online';
$l['online_users'] = 'Ovdje je trenutno <b>{1}</b> korisnika online.';
$l['online_counts'] = '<b>{1}</b> Član(ova) i <b>{2}</b> Gost(iju)';
$l['print_this_item'] = 'Ispiši ovo';
$l['send_to_friend'] = 'Pošalji ovo prijatelju';
$l['latest_announcements'] = 'Zadnje obavijesti';
$l['portal_disabled'] = 'Ne možete koristiti portal jer nije odobren od strane administratora.';
