<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sat, 03 Jun 2017 12:12:32 +0000
// --------------------------------------------------------------------------------

$l['nav_pms'] = 'Privatne poruke';
$l['nav_send'] = 'Sastavljanje';
$l['nav_tracking'] = 'Praćenje poruka';
$l['nav_folders'] = 'Upravljanje mapama';
$l['nav_empty'] = 'Prazne mape';
$l['nav_export'] = 'Izvezi poruke';
$l['nav_search'] = 'Traži';
$l['nav_results'] = 'Rezultati';
$l['new_pm'] = 'Nove poruke';
$l['old_pm'] = 'Stare poruke';
$l['reply_pm'] = 'Odgovoreno na';
$l['fwd_pm'] = 'Proslijeđena poruka';
$l['pms_disabled'] = 'Ne možete koristiti privatne poruke jer ta funkcija foruma nije odobrena od strane administratora.';
$l['private_messaging'] = 'Privatne poruke';
$l['inbox'] = 'Ulazni sandučić';
$l['compose_message2'] = 'Sastavljanje poruke';
$l['manage_folders'] = 'Upravljanje mapama';
$l['pm_search_results'] = 'Rezultati pretraživanja privatnih poruka';
$l['message_title'] = 'Naslov poruke';
$l['sender'] = 'Pošiljatelj';
$l['sentto'] = 'Za';
$l['date_sent'] = 'Datum/vrijeme slanja';
$l['desc'] = 'silazno';
$l['asc'] = 'uzlazno';
$l['delete_pm'] = 'Obriši';
$l['move_to'] = 'Premjesti u';
$l['or'] = 'ili';
$l['selected_messages'] = 'izabrane poruke';
$l['go'] = 'Idi!';
$l['pmspaceused'] = 'od PP prostora korišteno';
$l['jump_folder'] = 'Skoči na mapu:';
$l['archive_messages'] = 'Izvezi privatne poruke';
$l['archive_note'] = 'Slijedeći alat će biti preuzeti vaše privatne poruke izvan izabrane mape, poruke poslane nakon određenog datuma, vaše pročitane poruke i skice za kasniji pregled.';
$l['folders'] = 'Mape:';
$l['all_folders'] = 'Sve mape';
$l['date_limit'] = 'Ograničenje datuma:';
$l['date_limit_older'] = 'Izvezi poruke starije od';
$l['date_limit_newer'] = 'Izvezi poruke novije od';
$l['date_limit_disregard'] = 'Zanemarivanje datuma';
$l['date_limit_days'] = 'dana';
$l['export_unread'] = 'Izvezi nepročitane poruke?';
$l['delete_archived'] = 'Obriši izvezene poruke?';
$l['delete_archived_note'] = 'Želite li obrisati poruke iz mape kada ih izvezete?';
$l['export_format'] = 'Format datoteke za izvoz:';
$l['export_format_note'] = 'Molimo odaberite tip datoteke od kojih želite preuzeti priloge.';
$l['export_html'] = 'HTML datoteke (.html)';
$l['export_txt'] = 'Tekstualne datoteke (.txt)';
$l['export_csv'] = 'Uvozne MS Excel datoteke (.csv)';
$l['private_messages_for'] = 'Privatne poruke za {1}';
$l['exported_date'] = 'Izvezeno: {1}, {2}';
$l['subject'] = 'Naslov:';
$l['to'] = 'Za:';
$l['from'] = 'Od:';
$l['sent'] = 'Poslano:';
$l['export_messages2'] = 'Preuzmi poruke';
$l['empty_folders'] = 'Isprazni mape privatnih poruka';
$l['empty_folders2'] = 'Isprazni mape';
$l['empty_note'] = 'Here you can delete private messages from selected folders at one time. Simply select the folders you wish the messages to be deleted from and click \'Delete\'. You cannot undo these changes.<br /><strong>Note: Once these messages are deleted there is no way to recover them.</strong>';
$l['num_messages'] = 'Brojač poruka';
$l['empty_q'] = 'Prazni mapu?';
$l['keep_unread'] = 'Ostavi nepročitane poruke';
$l['pm_folders'] = 'Mape privatnih poruka';
$l['existing_folders'] = 'Postojeće mape';
$l['edit_folder_note'] = 'You can change the names of your current private messaging folders here. To delete a folder, delete the name of the folder. Some folders cannot be removed.<br /><strong>Note: Deleting a folder will also delete any messages in it.</strong>';
$l['new_folders'] = 'Dodaj nove mape';
$l['add_folders_note'] = 'Here you can create additional message folders. You do not have to fill in all of the text boxes.';
$l['update_folders'] = 'Ažuriraj mape';
$l['cannot_be_removed'] = 'Ne može biti maknuto';
$l['reached_warning'] = 'Upozorenje. Dosegli ste maksimum poruka.';
$l['reached_warning2'] = 'Da biste imali mogućnost primanja poruka trebate obrisati stare poruke.';
$l['deny_receipt'] = '[Deny Receipt]';
$l['viewing_pm'] = 'Gleda PP:';
$l['reply'] = 'Odgovori';
$l['reply_to_all'] = 'Odgovori svima';
$l['forward'] = 'Proslijedi';
$l['compose_pm'] = 'Sastavi privatnu poruku';
$l['compose_to'] = 'Primatelji:';
$l['compose_bcc'] = 'BCC:';
$l['compose_bcc_show'] = 'BCC';
$l['compose_bcc_show_title'] = 'Show the BCC input box allowing you to blind carbon copy messages to other users.';
$l['separate_names'] = 'Odvojite više korisničkih imena zarezom.';
$l['max_recipients'] = '<br />You may send this message to a maximum of <strong>{1}</strong> people.';
$l['compose_subject'] = 'Naslov:';
$l['compose_message'] = 'Poruka:';
$l['compose_options'] = 'Opcije:';
$l['message_icon'] = 'Ikona poruke:';
$l['options_sig'] = '<strong>Potpis:</strong> uključite vaš potpis u ovoj poruci';
$l['options_disable_smilies'] = '<strong>Onemogući smajliće:</strong> onemogući prikazivanje smajlića u poruci';
$l['options_save_copy'] = '<strong>Spremi kopiju:</strong> spremi kopiju ove poruke u sadučiću poslanih poruka';
$l['options_read_receipt'] = '<strong>Zahtjevaj čitanje primatelja:</strong> primi poruku kada ova poruka bude pročitana';
$l['send_message'] = 'Pošalji poruku';
$l['save_draft'] = 'Spremi kao skicu';
$l['preview'] = 'Pregled';
$l['select_buddy'] = 'Ili odaberi prijatelja';
$l['pm_tracking'] = 'Praćenje privatnih poruka';
$l['read_messages'] = 'Pročitane poruke';
$l['unread_messages'] = 'Nepročitane poruke';
$l['q'] = '?';
$l['dateread'] = 'Datum čitanja';
$l['stop_tracking'] = 'Prestani pratiti';
$l['datesent'] = 'Datum slanja';
$l['cancel'] = 'Odustani';
$l['export_date_sent'] = 'Datum';
$l['export_folder'] = 'Mapa';
$l['export_subject'] = 'Naslov';
$l['export_to'] = 'Za';
$l['export_from'] = 'Od';
$l['export_message'] = 'Poruka';
$l['not_sent'] = 'N/A (nije poslano)';
$l['at'] = 'u';
$l['nomessages'] = 'Nema privatnih poruka u ovoj mapi';
$l['details'] = 'Detalji';
$l['message'] = 'Poruka';
$l['buddy_list'] = 'Popis prijatelja';
$l['multiple_recipients'] = '<em>Više primatelja</em>';
$l['bcc'] = 'BCC:';
$l['reply_title'] = 'Odgovori na ovu privatnu poruku';
$l['forward_title'] = 'Proslijedi ovu privatnu poruku drugom korisniku';
$l['delete_title'] = 'Obriši ovu privatnu poruku';
$l['you_replied_on'] = 'Odgovorili ste na ovu privatnu poruku na {1}';
$l['you_forwarded_on'] = 'Proslijedili ste ovu poruku na {1}';
$l['you_replied'] = 'Odgovorili ste na poruku {1}';
$l['you_forwarded'] = 'Proslijedi ovu poruku {1}';
$l['select_from_buddies'] = 'Odaberi os prijatelja';
$l['no_readmessages'] = 'Trenutno nema pročitanih poruka koje su praćene.';
$l['no_unreadmessages'] = 'Trenutno nema nepročitanih poruka koje su praćene.';
$l['stop_tracking_all'] = 'Prestani pratiti sve poruke';
$l['enter_keywords'] = 'Unesi ključne riječi';
$l['advanced_search'] = 'Napredna pretraga';
$l['search_pms'] = 'Traži PP-e';
$l['advanced_private_message_search'] = 'Napredno pretraživanje privatnih poruka';
$l['search_criteria'] = 'Kriterij pretrage';
$l['keywords'] = 'Ključne riječi';
$l['search_in_subject'] = 'Traži u naslovu';
$l['search_in_message'] = 'Traži u poruci';
$l['message_status'] = 'Status poruke';
$l['message_status_new'] = 'Novo';
$l['message_status_replied_to'] = 'Odgovoreno';
$l['message_status_forwarded'] = 'Proslijeđeno';
$l['message_status_read'] = 'Pročitano';
$l['folder'] = 'Mapa';
$l['search_options'] = 'Opcije pretrage';
$l['sort_by'] = 'Složi po';
$l['sort_by_subject'] = 'Složi po: naslovu';
$l['sort_by_sender'] = 'Složi po: pošiljatelju';
$l['sort_by_date'] = 'Složi po: datumu';
$l['ascending_order'] = 'Uzlazni redoslijed';
$l['descending_order'] = 'Silazni redoslijed';
$l['search_private_messages'] = 'Pretraži privatne poruke';
$l['check_all'] = 'Označi sve';
$l['search_user'] = 'Traži korisnika';
$l['error_nopmsarchive'] = 'Sorry, but there are no private messages matching the criteria you specified.';
$l['error_invalidpmfoldername'] = 'Sorry, but a folder name you have entered contains characters which are not allowed.';
$l['error_emptypmfoldername'] = 'Sorry, but a folder name you have entered does not contain any text.  Please enter a name for the folder, or completely blank the name to delete the folder.';
$l['error_invalidpmrecipient'] = 'The recipient you entered is either invalid or doesn\'t exist. Please go back and enter a correct one.';
$l['error_invalidpm'] = 'Neispravan PP';
$l['error_pmrecipientreachedquota'] = 'You cannot send a private message to {1} because he/she has reached their private messaging quota. They cannot be sent any message until their messages have been cleared out. An email has been sent to the user about this. Please try sending your message at a later stage.';
$l['error_recipientpmturnedoff'] = '{1} has chosen not to receive private messages or may not be allowed to do so. Therefore you may not send your private message to this user.';
$l['error_pmsturnedoff'] = 'You currently have private messages disabled in your profile.<br />To be able to use the private messaging system this setting must be enabled.';
$l['error_recipientignoring'] = 'We are sorry but we cannot process your private message to {1}. You do not have permission to perform this action.';
$l['error_pm_already_submitted'] = 'You have already submitted the same private message to the same recipient within the last 5 minutes.';
$l['error_nopms'] = 'You must have one or more private messages in order to access this function.';
$l['error_minsearchlength'] = 'One or more of your search terms were shorter than the minimum length. The minimum search term length is {1} characters.<br /><br />If you\'re trying to search for an entire phrase, enclose it within double quotes. For example "The quick brown fox jumps over the lazy dog".';
$l['error_nosearchresults'] = 'Sorry, but no results were returned using the query information you provided. Please redefine your search terms and try again.';
$l['error_no_search_support'] = 'Ova databaza ne podržava traženje';
$l['error_nosearchterms'] = 'You did not enter any search terms. At a minimum, you must enter either some search terms or a username to search by.';
$l['error_searchflooding_1'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another 1 second before attempting to search again.';
$l['error_searchflooding'] = 'Sorry, but you can only perform one search every {1} seconds. Please wait another {2} seconds before attempting to search again.';
$l['error_invalidsearch'] = 'Navedena je neispravna pretraga. Molimo vas da se vratite natrag i pokušate ponovno.';
$l['redirect_pmsaved'] = 'Privatna poruka je spremljena u mapu za skice.';
$l['redirect_pmstrackingstopped'] = 'Praćenje odabranih PP-a je prestalo.';
$l['redirect_pmstrackingcanceled'] = 'The selected unread PMs have been deleted from the recipient\'s inbox.';
$l['redirect_allpmstrackingstopped'] = 'Tracking of all read PMs has been stopped.';
$l['redirect_pmsmoved'] = 'The selected private messages have been moved.';
$l['redirect_pmsdeleted'] = 'The selected private messages have been deleted.';
$l['redirect_pmsent'] = 'Thank you, your private message has successfully been sent.<br />You will now be returned to your private message inbox.';
$l['redirect_pmfoldersupdated'] = 'Thank you, your private messaging folders have successfully been updated.<br />You will now be returned to your private message Inbox.';
$l['redirect_pmfoldersemptied'] = 'The selected private messaging folders have successfully been emptied.<br />You will now be taken back to your Private Messaging Inbox.';
$l['redirect_searchresults'] = 'Thank you, your search has been submitted and you will now be taken to the results list.';
$l['quick_reply'] = 'Brzi odgovor';
$l['message_note'] = 'Napišite odgovor na ovu poruku ovdje.';
$l['send_reply'] = 'Pošalji odgovor';
$l['quickreply_signature'] = 'Potpis';
$l['quickreply_disable_smilies'] = 'Onemogući smajliće';
$l['quickreply_save_copy'] = 'Spremi kao kopiju';
$l['quickreply_read_receipt'] = '<strong>Zatraži primateljevo čitanje</strong>';
