<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1813
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sun, 19 Apr 2020 13:38:39 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = 'Hvala vam, tema je uspješno ocjenjena. Sada ćete biti vraćeni na temu.';
$l['error_invalidrating'] = 'Izabrali ste neispravnu ocjenu za ovu temu. molimo vas da se vratite natrag i pokušate ponovno.';
$l['error_alreadyratedthread'] = 'Žao nam je, već ste ocijenili ovu temu.';
$l['error_cannotrateownthread'] = 'Žao nam je, ne možete ocjenjivati vašu temu.';
$l['rating_votes_average'] = '{1} Glas(ova) - {2} od 5 u prosjeku';
$l['one_star'] = '1 zvijezda od 5';
$l['two_stars'] = '2 zvijezda od 5';
$l['three_stars'] = '3 zvijezda od 5';
$l['four_stars'] = '4 zvijezda od 5';
$l['five_stars'] = '5 zvijezda od 5';
$l['rating_added'] = 'Vaša ocjena je dodana!';
$l['thread_doesnt_exist'] = 'Ne možete ocjeniti temu koja ne postoji.';
