<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hrvatski (Croatian)
// Author of the language pack : Ivan Kerepčić
// Language pack translators website : http://ivankerepcic.iz.hr/
// Compatible version of MyBB : 1813
// Last edited in MyBB Editor by : Ikerepc
// Last edited date : Sun, 19 Apr 2020 13:39:39 +0000
// --------------------------------------------------------------------------------

$l['nav_reputation'] = 'Prijava reputacije';
$l['nav_profile'] = 'Profil od {1}';
$l['reputation_disabled'] = 'Ne možete koristiti sistem reputacije jer nije odobren od strane administratora.';
$l['reputation'] = 'Reputacija';
$l['error'] = 'Greška';
$l['add_no_uid'] = 'Niste naveli korisnika kojemu dajete reputaciju.';
$l['add_no_permission'] = 'Nemate dopuštenje da biste dali reputaciju korisnicima.';
$l['add_disabled'] = 'Ne možete dodati reputaciju korisnicima ove grupe.';
$l['add_yours'] = 'Ne možete dati reputaciju samome sebi.';
$l['add_invalidpower'] = 'Niste odabrali ispravnu ocjenu s popisa.';
$l['add_maxperday'] = 'Dali ste maksimum reputacije koliko vam je dozvoljeno za danas.';
$l['add_maxperuser'] = 'Već ste dali ovome korisniku reputacije koliko vam je dozvoljeno za danas.';
$l['add_maxperthread'] = 'Dali ste maksimum reputacije ovome korisniku (u jednoj temi) koliko vam je dozvoljeno za danas.';
$l['add_no_comment'] = 'Morate unijeti komentar od najmanje {1} znakova da biste dali ovome korinsiku reputaciju.';
$l['add_toolong'] = 'Razlog ne smije biti veći od {1} znakova.';
$l['add_negative_disabled'] = 'Administrator ne dopušta negativne reputacije.';
$l['add_neutral_disabled'] = 'Administartor ne dopušta neutralne reputacije.';
$l['add_positive_disabled'] = 'Administartor ne dopušta pozitivne reputacije.';
$l['add_all_rep_disabled'] = 'Administartor ne dopušta nikakve reputacije. Ne možete ocijeniti ovoga korisnika.';
$l['reputation_report'] = 'Prijava reputacije za {1}';
$l['reputation_members'] = 'Reputacija od korisnika:';
$l['reputation_posts'] = 'Reputacije iz postova:';
$l['summary'] = 'Pregled';
$l['total_reputation'] = 'Ukupna reputacija';
$l['post_reputation'] = 'Pošalji reputaciju';
$l['positive_count'] = 'Pozitivno';
$l['neutral_count'] = 'Neutralno';
$l['negative_count'] = 'Negativno';
$l['last_week'] = 'Zadnji tjedan';
$l['last_month'] = 'Zadnji mjesec';
$l['last_6months'] = 'Zadnjih 6 mjeseci';
$l['all_time'] = 'Sve vrijeme';
$l['comments'] = 'Komentari';
$l['close_window'] = 'Zatvori prozor';
$l['add_reputation_vote'] = 'Dodaj reputaciju za {1}';
$l['add_reputation_to_post'] = 'Ova reputacija je za {1} post.<br />';
$l['neg_rep_disabled'] = '<span class="smalltext">* - <em>Negativna reputacija trenutno nije dozvoljena</em></span>';
$l['pos_rep_disabled'] = '<span class="smalltext">* - <em>Pozitivna reputacija trenutno nije dozvoljena</em></span>';
$l['neu_rep_disabled'] = '<span class="smalltext">* - <em>Neutralna reputacija trenutno nije dozvoljena</em></span>';
$l['no_comment_needed'] = 'Vi dodajete reputaciju zbog korisničkog posta, čiji je liku u njegovom profilu. Komentar nije potreban, ali ako ga želite ostaviti, molimo vas da ga navedete ispod.<br />';
$l['no_comment'] = '[Bez komentara]';
$l['vote_added'] = 'Reputacija dodana';
$l['vote_updated'] = 'Ocjena ažurirana';
$l['vote_deleted'] = 'Ocjena obrisana';
$l['vote_added_message'] = 'Vaša reputacijska ocjena je uspješno dodana korisniku.';
$l['vote_updated_message'] = 'Vaša reputacijska ocjena je uspješno ažurirana ovom korisniku.';
$l['vote_deleted_message'] = 'Vaša reputacijska ocjena je uspješno obrisana ovom korisniku.';
$l['update_reputation_vote'] = 'Ažuriraj vašu reputacijsku ocjenu za {1}';
$l['positive'] = 'Pozitovno';
$l['negative'] = 'Negativno';
$l['neutral'] = 'Neutralno';
$l['user_comments'] = 'Vaši komentari na {1}:';
$l['add_vote'] = 'Dodaj ocjenu';
$l['update_vote'] = 'Ažuriraj ocjenu';
$l['delete_vote'] = 'Obriši';
$l['report_vote'] = 'Prijavi';
$l['power_positive'] = 'Pozitivno ({1})';
$l['power_neutral'] = 'Neutralno';
$l['power_negative'] = 'Negativno ({1})';
$l['show_all'] = 'Prikaži: sve glasove';
$l['show_positive'] = 'Prikaži: pozitivne glasove';
$l['show_neutral'] = 'Prikaži: neutralne glasove';
$l['show_negative'] = 'Prikaži: negativne glasove';
$l['sort_updated'] = 'Složi po: zadnje ažurirano';
$l['sort_username'] = 'Složi po: korisničkom imenu';
$l['last_updated'] = 'Zadnje ažurirano {1}';
$l['postrep_given'] = 'Ocjena dana za <a href="{1}">{2} post</a> {3}<br />';
$l['postrep_given_thread'] = 'u <a href="{1}">{2}</a>';
$l['no_reputation_votes'] = 'Ovaj korisnik trenutno nema reputacijeskih ocjena s navedenim kriterijima ispod.';
$l['delete_reputation_confirm'] = 'Jeste li sigurni da želite obrisati ovu reputacijsku ocjenu?';
$l['delete_reputation_log'] = 'Obrisana reputacijska ocjena od {1} (UID: {2})';
$l['reputations_disabled_group'] = 'Reputacijski sistem nije dopušten za korisnike ove korisničke grupe.';
$l['rate_user'] = 'Ocijeni korisnika';
$l['postrep_given_nolink'] = 'Reputacija dana za post korisnika {1}<br />';
