version: '3.8'

services:
  openssh-server:
    image: linuxserver/openssh-server
    container_name: openssh-server
    restart: unless-stopped
    hostname: openssh-server #optional
    # https://github.com/linuxserver/docker-mods/tree/openssh-server-ssh-tunnel
    expose:
      - 1081 # for traefik
    ports:
      - 22:2222 # can do 22
    environment:
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
      - SHELL_NOLOGIN=false
      # set correct for current host user
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      # forward env var, important
      - PUBLIC_KEY 
      - SUDO_ACCESS=true #optional
      - USER_NAME=username #optional
      - PASSWORD_ACCESS=false #optional
      # - USER_PASSWORD=password #optional
      # - PUBLIC_KEY_FILE=/path/to/file #optional
      # - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      # - PUBLIC_KEY_URL=https://github.com/username.keys #optional
      # - USER_PASSWORD_FILE=/path/to/file #optional
      # - LOG_STDOUT= #optional
    volumes:
      - ./config:/config 
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.ssh-server.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.ssh-server.entrypoints=websecure'
      - 'traefik.http.routers.ssh-server.service=ssh-server'
      - 'traefik.http.services.ssh-server.loadbalancer.server.port=1081'
    networks:
      - proxy

networks:
  proxy:
    external: true