# prod file

services:
  hn-new-jobs:
    container_name: hn-new-jobs
    restart: unless-stopped
    image: nemanjamitic/hn-new-jobs:latest
    # use single .env
    env_file:
      - .env
    environment:
      - PORT=3007
    # fixes file permissions for volume
    # uid=1000(username) gid=1000(username)
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - ./data:/app/data
    networks:
      - proxy
    labels:
      # Common
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'

      # Old
      # - 'traefik.http.routers.hn-new-jobs-secure.rule=Host(`${SITE_HOSTNAME}`)'
      # - 'traefik.http.routers.hn-new-jobs-secure.entrypoints=websecure'
      # - 'traefik.http.routers.hn-new-jobs-secure.service=hn-new-jobs-svc'
      # - 'traefik.http.services.hn-new-jobs-svc.loadbalancer.server.port=3007'

      # New
      # Main router
      - 'traefik.http.routers.hn-new-jobs.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.hn-new-jobs.entrypoints=websecure'
      - 'traefik.http.routers.hn-new-jobs.service=hn-new-jobs'
      - 'traefik.http.services.hn-new-jobs.loadbalancer.server.port=3007'

      # Redirect router
      - 'traefik.http.routers.hn-new-jobs-redirect-www.rule=Host(`www.${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.hn-new-jobs-redirect-www.entrypoints=websecure'
      - 'traefik.http.routers.hn-new-jobs-redirect-www.middlewares=hn-new-jobs-redirect-to-non-www'
      - 'traefik.http.routers.hn-new-jobs-redirect-www.service=noop@internal'

      # Middleware to redirect to non-www
      - 'traefik.http.middlewares.hn-new-jobs-redirect-to-non-www.redirectregex.regex=^https://www\.(.+)'
      - 'traefik.http.middlewares.hn-new-jobs-redirect-to-non-www.redirectregex.replacement=https://$$1'
      - 'traefik.http.middlewares.hn-new-jobs-redirect-to-non-www.redirectregex.permanent=true'

networks:
  proxy:
    external: true
