[client]
remote_addr = "152.70.160.21:2333"

[client.transport]
type = "noise"

[client.transport.noise]
remote_public_key = "public_key"

# this is most important
# rathole knows traffic comes from 5080 and 5443, controll chanell told him
# DONT do ANY mapping in docker-compose, just pass traffic from rathole on ports traefik expects
# in same docker-compose.yml for depends_on
[client.services.traefik-http]
token = "my-secret"
local_addr = "traefik:80"

[client.services.traefik-https]
token = "my-secret"
local_addr = "traefik:443"  

