# prod file
name: githubcities

services:
  frontend:
    image: nemanjamitic/githubcities-frontend:latest
    container_name: githubcities-frontend
    restart: unless-stopped
    # Todo: use .env, .env.frontend, .env.backend
    # use single .env
    env_file:
      - .env
    environment:
      - PORT=3000
    # fixes file permissions for volume
    # uid=1000(username) gid=1000(username)
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - ./data:/app/data
    networks:
      - default
      - proxy
    labels:
      # Common
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'

      # New
      # Main router
      - 'traefik.http.routers.githubcities-frontend.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.githubcities-frontend.entrypoints=websecure'
      - 'traefik.http.routers.githubcities-frontend.service=githubcities-frontend'
      - 'traefik.http.services.githubcities-frontend.loadbalancer.server.port=3000'

      # Redirect router
      - 'traefik.http.routers.githubcities-frontend-redirect-www.rule=Host(`www.${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.githubcities-frontend-redirect-www.entrypoints=websecure'
      - 'traefik.http.routers.githubcities-frontend-redirect-www.middlewares=githubcities-frontend-redirect-to-non-www'
      - 'traefik.http.routers.githubcities-frontend-redirect-www.service=noop@internal'

      # Middleware to redirect to non-www
      - 'traefik.http.middlewares.githubcities-frontend-redirect-to-non-www.redirectregex.regex=^https://www\.(.+)'
      - 'traefik.http.middlewares.githubcities-frontend-redirect-to-non-www.redirectregex.replacement=https://$$1'
      - 'traefik.http.middlewares.githubcities-frontend-redirect-to-non-www.redirectregex.permanent=true'

  backend:
    image: nemanjamitic/githubcities-backend:latest
    container_name: githubcities-backend
    restart: unless-stopped
    # don't mount alembic as volume
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - default
      - proxy

    labels:
      # Common
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'

      # No www. support
      - 'traefik.http.routers.githubcities-backend.rule=Host(`api.${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.githubcities-backend.entrypoints=websecure'
      - 'traefik.http.routers.githubcities-backend.service=githubcities-backend'
      - 'traefik.http.services.githubcities-backend.loadbalancer.server.port=8000'

  database:
    image: postgres:17.5-alpine3.22
    container_name: githubcities-database
    restart: unless-stopped
    user: '${MY_UID}:${MY_GID}'
    # ports:
    #   - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    volumes:
      - ./backend/data/database:/var/lib/postgresql/data # !without pgdata
    networks:
      - default # not on public network

  adminer:
    image: adminer:5.4.0-standalone
    container_name: githubcities-adminer
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - ADMINER_DESIGN=nicu
    networks:
      - default
      - proxy
    labels:
      # Common
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'

      # No www. support
      - 'traefik.http.routers.githubcities-adminer.rule=Host(`adminer.${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.githubcities-adminer.entrypoints=websecure'
      - 'traefik.http.routers.githubcities-adminer.service=githubcities-adminer'
      - 'traefik.http.services.githubcities-adminer.loadbalancer.server.port=8080'


networks:
  default:
    driver: bridge
  proxy:
    external: true
