version: '3.8'

services:
  dokku:
    container_name: dokku
    # image: dokku/dokku:0.30.1
    build:
      context: .
      # install pack in Dockerfile
      dockerfile: Dockerfile
    ports:
      - '3022:22'
      # this exposes all app containers and not dokku container
      # - '8443:443'
      # - '8080:80'
      - '443:443'
      - '5001:80'
    environment:
      - DOKKU_HOSTNAME=dokku.${SERVER_HOSTNAME}
      - DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku
    volumes:
      - ./dokku-data:/mnt/dokku
      - /var/run/docker.sock:/var/run/docker.sock

    # networks:
    #   - proxy
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.docker.network=proxy'
    #   # traefik will handle letsencrypt
    #   - 'traefik.http.routers.dokku-http.rule=HostRegexp(`{subdomain:[[:ascii:]]+}.dokku.${SERVER_HOSTNAME}`)'
    #   - 'traefik.http.routers.dokku-http.entrypoints=web'
    #   # dokku default exposes 80 and 443
    #   - 'traefik.http.services.dokku-http.loadbalancer.server.port=80'
    #   # passthrough https
    #   - 'traefik.tcp.routers.dokku-https.tls=true'
    #   - 'traefik.tcp.routers.dokku-https.tls.passthrough=true'
    #   - 'traefik.tcp.routers.dokku-https.rule=HostSNIRegexp(`{subdomain:[[:ascii:]]+}.dokku.${SERVER_HOSTNAME}`)'
    #   - 'traefik.tcp.routers.dokku-https.entrypoints=websecure'
    #   - 'traefik.tcp.services.dokku-https.loadbalancer.server.port=443'

networks:
  proxy:
    external: true

  # 8080 -> 8080 -> traefik
  # 8443 -> 8443 -> traefik
  # take dokku apps trafic from default network and forward it to traefik
  # port-forward:
  #   container_name: port-forward
  #   image: alpine/socat:1.7.4.4
  #   command: tcp-listen:8080,fork,reuseaddr tcp-connect:dokku:8080 & tcp-listen:8443,fork,reuseaddr tcp-connect:dokku:8443 &
  #   restart: unless-stopped
  #   depends_on:
  #     - dokku
  #   networks:
  #     - proxy
  #     - default
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.docker.network=proxy'
  #     # traefik will handle letsencrypt
  #     - 'traefik.http.routers.dokku-http.rule=HostRegexp(`{subdomain:[[:ascii:]]+}.dokku.${SERVER_HOSTNAME}`)'
  #     - 'traefik.http.routers.dokku-http.entrypoints=web'
  #     # dokku default exposes 80 and 443
  #     - 'traefik.http.services.dokku-http.loadbalancer.server.port=8080'
  #     # passthrough https
  #     - 'traefik.tcp.routers.dokku-https.tls=true'
  #     - 'traefik.tcp.routers.dokku-https.tls.passthrough=true'
  #     - 'traefik.tcp.routers.dokku-https.rule=HostSNIRegexp(`{subdomain:[[:ascii:]]+}.dokku.${SERVER_HOSTNAME}`)'
  #     - 'traefik.tcp.routers.dokku-https.entrypoints=websecure'
  #     - 'traefik.tcp.services.dokku-https.loadbalancer.server.port=8443'
