version: '3.8'

services:
  dokku:
    container_name: dokku
    # image: dokku/dokku:0.30.3
    build:
      context: .
      # install pack in Dockerfile
      dockerfile: Dockerfile
    ports:
      - '3022:22'
      # this exposes all app containers and not dokku container
      # - '8443:443'
      # - '8080:80'
    environment:
      - DOKKU_HOSTNAME=dokku.${SERVER_HOSTNAME}
      - DOKKU_HOST_ROOT=${PWD}/dokku-data/home/dokku
    volumes:
      - ${PWD}/dokku-data:/mnt/dokku
      - ${PWD}/plugin-list:/mnt/dokku/plugin-list
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
      - dokku-external
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      # entrypoints.websecure - traefik will handle letsencrypt
      # entrypoints.web - will pass http
      - 'traefik.http.routers.dokku-http.entrypoints=websecure'
      - 'traefik.http.routers.dokku-http.rule=HostRegexp(`{subdomain:[a-z1-9\-]+}.dokku.${SERVER_HOSTNAME}`)'
      # dokku default exposes 80 and 443
      - 'traefik.http.services.dokku-http.loadbalancer.server.port=80'
      # passthrough https
      # curl: (35) error:0A000126:SSL routines::unexpected eof while reading
      # - 'traefik.tcp.routers.dokku-https.tls=true'
      # - 'traefik.tcp.routers.dokku-https.tls.passthrough=true'
      # - 'traefik.tcp.routers.dokku-https.entrypoints=websecure'
      # - 'traefik.tcp.routers.dokku-https.rule=HostSNIRegexp(`{subdomain:[a-z1-9\-]+}.dokku.${SERVER_HOSTNAME}`)'
      # - 'traefik.tcp.services.dokku-https.loadbalancer.server.port=443'

networks:
  proxy:
    external: true
  dokku-external:
    external: true
