version: '3.8'

services:
  dokku:
    # image: dokku/dokku:0.29.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dokku
    ports:
      - '3022:22'
      - '443:443'
      - '80:80'
    environment:
      - DOKKU_HOSTNAME=dokku.${DOMAIN}
      - DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku
      # - BUILDPACK_URL=https://github.com/paketo-buildpacks/nodejs.git
    volumes:
      - ./dokku-data:/mnt/dokku
      - /var/run/docker.sock:/var/run/docker.sock
      # mount pack binary
      # - /usr/local/bin/pack:/usr/local/bin/pack
      # - /var/lib/dokku:/mnt/dokku

    # dokku must handle routing, it generates apps subdomains
    # networks:
    #   - proxy
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.docker.network=proxy'
    #   - 'traefik.http.routers.dokku-https.rule=Host(`dokku.${DOMAIN}`)'
    #   - 'traefik.http.routers.dokku-https.entrypoints=websecure'
    #   - 'traefik.http.routers.dokku-https.service=dokku-svc'
    #   - 'traefik.http.services.dokku-svc.loadbalancer.server.port=80'
# networks:
#   proxy:
#     external: true
