version: '3.9'

services:
  nmc-docker:
    image: nemanjamitic/nemanjam.github.io:latest
    container_name: nmc-docker
    restart: unless-stopped
    networks:
      - proxy
    labels:
      # Common
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'

      # Old
      # - 'traefik.http.routers.nmc-docker-secure.rule=Host(`${SITE_HOSTNAME}`)'
      # - 'traefik.http.routers.nmc-docker-secure.entrypoints=websecure'
      # - 'traefik.http.routers.nmc-docker-secure.service=nmc-docker'
      # # nginx.conf and Dockerfile
      # - 'traefik.http.services.nmc-docker.loadbalancer.server.port=8080'

      # New
      # Main router
      - 'traefik.http.routers.nmc-docker.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.nmc-docker.entrypoints=websecure'
      - 'traefik.http.routers.nmc-docker.service=nmc-docker'
      - 'traefik.http.services.nmc-docker.loadbalancer.server.port=8080'

      # Redirect router
      - 'traefik.http.routers.nmc-docker-redirect-www.rule=Host(`www.${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.nmc-docker-redirect-www.entrypoints=websecure'
      - 'traefik.http.routers.nmc-docker-redirect-www.middlewares=nmc-docker-redirect-to-non-www'
      - 'traefik.http.routers.nmc-docker-redirect-www.service=noop@internal'

      # Middleware to redirect to non-www
      - 'traefik.http.middlewares.nmc-docker-redirect-to-non-www.redirectregex.regex=^https://www\\.(.+)'
      - 'traefik.http.middlewares.nmc-docker-redirect-to-non-www.redirectregex.replacement=https://$$\\1'
      - 'traefik.http.middlewares.nmc-docker-redirect-to-non-www.redirectregex.permanent=true'


networks:
  proxy:
    external: true
