version: '3.8'

services:
  nmc-docker:
    image: nemanjamitic/astro-blog:0.0.1
    container_name: nmc-docker
    environment:
    # - PUBLIC_SITE_HOSTNAME # https:// + SITE_HOSTNAME
    # - PORT
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.nmc-docker-secure.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.nmc-docker-secure.entrypoints=websecure'
      - 'traefik.http.routers.nmc-docker-secure.service=nmc-docker'
      - 'traefik.http.services.nmc-docker.loadbalancer.server.port=8080'

networks:
  proxy:
    external: true
