version: '3.8'

services:
  nmc-docker:
    image: nemanjamitic/nemanjam.github.io:latest
    container_name: nmc-docker
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.nmc-docker-secure.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.nmc-docker-secure.entrypoints=websecure'
      - 'traefik.http.routers.nmc-docker-secure.service=nmc-docker'
      # nginx.conf and Dockerfile
      - 'traefik.http.services.nmc-docker.loadbalancer.server.port=8080'

networks:
  proxy:
    external: true
