api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: nemanja.mitic.elfak@hotmail.com
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
