version: '3.9'

# alternative 1 - inject separate env files into containers
# env_file:
#   - ./client/.env
# env_file:
#   - ./server/.env
#
# alternative 2 - put all vars into single .env and forward vars through docker-compose.yml
# environment: ...

services:
  mdp-client:
    container_name: mdp-client
    restart: unless-stopped
    image: nemanjamitic/mern-boilerplate-client:latest
    depends_on:
      - mdp-server
    networks:
      - internal-client
      - proxy
    environment:
      - NODE_ENV=production
      # forwarded
      - REACT_APP_BASE_URL
    # env_file:
    #   - ./client/.env

    # nginx ports
    # either open port or route through traefik
    # ports:
    # - '3080:80'
    # - '3443:443' # must edit nginx.conf

    # handles everything except /api and /public/images
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.mb-client-secure.rule=Host(`${SITE_HOSTNAME}`) && !(PathPrefix(`/api`) || PathPrefix(`/auth`) || PathPrefix(`/public/images`))'
      - 'traefik.http.routers.mb-client-secure.entrypoints=websecure'
      - 'traefik.http.routers.mb-client-secure.service=mb-client-svc'
      - 'traefik.http.services.mb-client-svc.loadbalancer.server.port=80'

  mdp-server:
    container_name: mdp-server
    restart: unless-stopped
    image: nemanjamitic/mern-boilerplate-server:latest
    depends_on:
      - mdp-mongo
    environment:
      - NODE_ENV=production
      # forwarded
      - MONGO_URI_PROD
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CALLBACK_URL
      - FACEBOOK_APP_ID
      - FACEBOOK_SECRET
      - FACEBOOK_CALLBACK_URL
      - JWT_SECRET_PROD
      - CLIENT_URL_PROD
      - SERVER_URL_PROD
    # env_file:
    #   - ./server/.env
    networks:
      - default
      - internal-client
      - proxy
    volumes:
      - ./server/public/images:/home/node/app/server/public/images

    # either open port or route through traefik
    # ports:
    #   - '5000:5000'

    # must be exposed through traefik too
    # handles /api and /public/images
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.mb-server-secure.rule=Host(`${SITE_HOSTNAME}`) && (PathPrefix(`/api`) || PathPrefix(`/auth`) || PathPrefix(`/public/images`))'
      - 'traefik.http.routers.mb-server-secure.entrypoints=websecure'
      - 'traefik.http.routers.mb-server-secure.service=mb-server-svc'
      - 'traefik.http.services.mb-server-svc.loadbalancer.server.port=80'

  mdp-mongo:
    image: mongo:6.0.3
    container_name: mdp-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      # forwarded
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    # env_file:
    #   - ./server/.env
    volumes:
      - ./server/docker/mongo-data:/data/db
    networks:
      - default

networks:
  internal-client:
    internal: true
  default:
    internal: true
  proxy:
    external: true
