version: '3.9'

services:
  nmc-nginx-with-volume:
    image: nginx:1.29.1-alpine3.22-slim
    container_name: nmc-nginx-with-volume
    restart: unless-stopped
    volumes:
      - ./website:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy
    labels:
      # Common
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'

      # Old
      # - 'traefik.http.routers.nmc-nginx-with-volume.rule=Host(`${SITE_HOSTNAME}`)'
      # - 'traefik.http.routers.nmc-nginx-with-volume.entrypoints=websecure'
      # - 'traefik.http.routers.nmc-nginx-with-volume.service=nmc-nginx-with-volume'
      # - 'traefik.http.services.nmc-nginx-with-volume.loadbalancer.server.port=8080'

      # New
      # Main router
      - 'traefik.http.routers.nmc-nginx-with-volume.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.nmc-nginx-with-volume.entrypoints=websecure'
      - 'traefik.http.routers.nmc-nginx-with-volume.service=nmc-nginx-with-volume'
      - 'traefik.http.services.nmc-nginx-with-volume.loadbalancer.server.port=8080'

      # Redirect router
      - 'traefik.http.routers.nmc-nginx-with-volume-redirect-www.rule=Host(`www.${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.nmc-nginx-with-volume-redirect-www.entrypoints=websecure'
      - 'traefik.http.routers.nmc-nginx-with-volume-redirect-www.middlewares=nmc-nginx-with-volume-redirect-to-non-www'
      - 'traefik.http.routers.nmc-nginx-with-volume-redirect-www.service=noop@internal'

      # Middleware to redirect to non-www
      - 'traefik.http.middlewares.nmc-nginx-with-volume-redirect-to-non-www.redirectregex.regex=^https://www\.(.+)'
      - 'traefik.http.middlewares.nmc-nginx-with-volume-redirect-to-non-www.redirectregex.replacement=https://$$1'
      - 'traefik.http.middlewares.nmc-nginx-with-volume-redirect-to-non-www.redirectregex.permanent=true'

networks:
  proxy:
    external: true
