version: '3.8'

services:
  nmc-nginx-with-volume:
    image: nginx:stable-alpine3.17-slim
    container_name: nmc-nginx-with-volume
    restart: unless-stopped
    volumes:
      - ./website:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.nmc-nginx-with-volume.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.nmc-nginx-with-volume.entrypoints=websecure'
      - 'traefik.http.routers.nmc-nginx-with-volume.service=nmc-nginx-with-volume'
      - 'traefik.http.services.nmc-nginx-with-volume.loadbalancer.server.port=8080'

networks:
  proxy:
    external: true
