version: '3.8'

services:
  multistep-form:
    container_name: multistep-form
    image: nemanjamitic/multistep-form:latest
    restart: unless-stopped
    environment:
      - PORT=3006
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.multistep-form-secure.rule=Host(`${SITE_HOSTNAME}`)'
      - 'traefik.http.routers.multistep-form-secure.entrypoints=websecure'
      - 'traefik.http.routers.multistep-form-secure.service=multistep-form-svc'
      - 'traefik.http.services.multistep-form-svc.loadbalancer.server.port=3006'

networks:
  proxy:
    external: true
